### ISSUE TITLE
ParentPeakMower cannot be applied to MS level 1

### ISSUE THREAD

**Issue by sagitter** [OpenMS/OpenMS#1389]
Hi all.

run_nose.py fails for me with this error (full log: https://kojipkgs.fedoraproject.org//work/tasks/9549/9619549/build.log):

```
FNon-fatal error while loading '/builddir/build/BUILD/OpenMS-Release2.0.0/pyOpenMS/tests/unittests/test.pep.xml': Cannot get precursor information - no experiment given
.......Will analyse 2 peptides with a total of 5 transitions 
.............Found no signal. The gaussian width is probably smaller than the spacing in your profile data. Try to use a bigger width. The error occured in the spectrum with retention time 4201.26.
Found no signal. The gaussian width is probably smaller than the spacing in your profile data. Try to use a bigger width. The error occured in the spectrum with retention time 4201.49.
Found no signal. The gaussian width is probably smaller than the spacing in your profile data. Try to use a bigger width. The error occured in the spectrum with retention time 4201.77.
........Error: ParentPeakMower cannot be applied to MS level 1
Error: ParentPeakMower cannot be applied to MS level 1
...................
======================================================================
ERROR: unittests.test000.testKernelMassTrace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/OpenMS-Release2.0.0/pyOpenMS/tests/unittests/test000.py", line 20, in wrapper
    f(*a, **kw)
  File "/builddir/build/BUILD/OpenMS-Release2.0.0/pyOpenMS/tests/unittests/test000.py", line 4149, in testKernelMassTrace
    assert trace.getScanTime is not None
AttributeError: 'pyopenms.pyopenms.Kernel_MassTrace' object has no attribute 'getScanTime'
======================================================================
FAIL: test_readfile (unittests.test_FileIO.TestIndexedMzMLFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/OpenMS-Release2.0.0/pyOpenMS/tests/unittests/test_FileIO.py", line 99, in test_readfile
    self.assertTrue(f.getParsingSuccess())
AssertionError: False is not true
======================================================================
FAIL: test_readfile_content (unittests.test_FileIO.TestIndexedMzMLFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/OpenMS-Release2.0.0/pyOpenMS/tests/unittests/test_FileIO.py", line 105, in test_readfile_content
    self.assertEqual( f.getNrSpectra() ,  2)
AssertionError: 0 != 2
======================================================================
FAIL: test_readfile (unittests.test_FileIO.TestIndexedMzMLFileLoader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/OpenMS-Release2.0.0/pyOpenMS/tests/unittests/test_FileIO.py", line 62, in test_readfile
    self.assertTrue(success)
AssertionError: False is not true
======================================================================
FAIL: test_readfile_content (unittests.test_FileIO.TestIndexedMzMLFileLoader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/OpenMS-Release2.0.0/pyOpenMS/tests/unittests/test_FileIO.py", line 68, in test_readfile_content
    self.assertEqual( e.getNrSpectra() ,  2)
AssertionError: 0 != 2
----------------------------------------------------------------------
Ran 220 tests in 21.851s
FAILED (errors=1, failures=4)
IsobaricNormalizer: max ratio deviation of alternative method is 0%
<IsobaricNormalizer: max ratio deviation of alternative method is 0%> occurred 3 times
<Non-fatal error while loading '/builddir/build/BUILD/OpenMS-Release2.0.0/pyOpenMS/tests/unittests/test.pep.xml': Cannot get precursor information - no experiment given> occurred 6 times
```

Previously, 'run_nose.py' is failed (full log:https://kojipkgs.fedoraproject.org//work/tasks/8036/9618036/build.log) with something like this:

```
While loading '/builddir/build/BUILD/OpenMS-Release2.0.0/pyOpenMS/tests/unittests/test2.mzML': Name of CV term not correct: 'MS:1000564 - PSI mzData file' should be 'PSI mzData format'
...........While loading '/builddir/build/BUILD/OpenMS-Release2.0.0/pyOpenMS/tests/unittests/test.indexed.mzML': Name of CV term not correct: 'MS:1000615 - ProteoWizard' should be 'ProteoWizard software'
..Non-fatal error while loading '/builddir/build/BUILD/OpenMS-Release2.0.0/pyOpenMS/tests/unittests/test.pep.xml': Cannot get precursor information - no experiment given
.......Will analyse 2 peptides with a total of 5 transitions 
.............Found no signal. The gaussian width is probably smaller than the spacing in your profile data. Try to use a bigger width. The error occured in the spectrum with retention time 4201.26.
Found no signal. The gaussian width is probably smaller than the spacing in your profile data. Try to use a bigger width. The error occured in the spectrum with retention time 4201.49.
Found no signal. The gaussian width is probably smaller than the spacing in your profile data. Try to use a bigger width. The error occured in the spectrum with retention time 4201.77.
........Error: ParentPeakMower cannot be applied to MS level 1
Error: ParentPeakMower cannot be applied to MS level 1
```

I have tested a patch that it's created just by following above warnings and i haven't idea if it's a good choice:

```
--- src/pyOpenMS/tests/unittests/test.indexed.orig.mzML 2015-04-09 17:57:04.000000000 +0200
+++ src/pyOpenMS/tests/unittests/test.indexed.mzML  2015-05-01 21:50:40.523915224 +0200
@@ -28,7 +28,7 @@
            <cvParam cvRef="MS" accession="MS:1000799" name="custom unreleased software tool" value="" />
        </software>
        <software id="so_dp_sp_0_pm_0" version="1.4.0" >
-           <cvParam cvRef="MS" accession="MS:1000615" name="ProteoWizard" />
+           <cvParam cvRef="MS" accession="MS:1000615" name="ProteoWizard software" />
        </software>
        <software id="so_dp_sp_0_pm_1" version="1.11.0" >
            <cvParam cvRef="MS" accession="MS:1000757" name="FileFilter" />
@@ -274,4 +274,4 @@
   </indexList>
   <indexListOffset>655460</indexListOffset>
 <fileChecksum>0</fileChecksum>
-</indexedmzML>
\ No newline at end of file
+</indexedmzML>
--- src/pyOpenMS/tests/unittests/test2.orig.mzML    2015-04-09 17:57:04.000000000 +0200
+++ src/pyOpenMS/tests/unittests/test2.mzML 2015-05-01 21:49:41.658250791 +0200
@@ -11,7 +11,7 @@
        <sourceFileList count="1">
            <sourceFile id="sf_ru_0" name="file://IBT-RABEAM/Data/andersm/B08-08318.RAW" location="">
                <cvParam cvRef="MS" accession="MS:1000569" name="SHA-1" value="8050207fea87c7c97555c6bb83fa50312b24fbbe" />
-               <cvParam cvRef="MS" accession="MS:1000564" name="PSI mzData file" />
+               <cvParam cvRef="MS" accession="MS:1000564" name="PSI mzData format" />
                <cvParam cvRef="MS" accession="MS:1000777" name="spectrum identifier nativeID format" />
            </sourceFile>
        </sourceFileList>
@@ -304,4 +304,4 @@
            </spectrum>
        </spectrumList>
    </run>
-</mzML>
\ No newline at end of file
+</mzML>
```

**Comment by hroest** [comment]
Hi @sagitter your patch looks good but only fixes the warnings which are non-fatal. I think you ran into an issue that was fixed with #1290 - can you try to apply that patch and see whether it works?

**Comment by sagitter** [comment]
It should be fixed, i'm compiling the commit 88dc253b95db54419bd484ffb07697193491484b but i still have memleak errors. Please, see https://kojipkgs.fedoraproject.org//work/tasks/6257/9996257/build.log

**Comment by cbielow** [comment]
Are these memleaks python-specific or is C++ code leaking memory?

**Comment by sagitter** [comment]
It's  ```run_memleaks.py``` test executed in the pyOpenMS directory (Python2.7).

**Comment by cbielow** [comment]
Yes, but would it also detect mem leaks within C++ code? I don't know the runtime interacts and how free__mem () works....
-- 
Sent via mobile phone.

Am 10. Juni 2015 19:38:59 MESZ, schrieb Antonio <notifications@github.com>:

**Comment by sagitter** [comment]
Honestly, i don't know what reply. Can i do something to "discover it"?

**Comment by cbielow** [comment]
I was hoping our python experts could comment :)

Am 6/11/2015 um 00:02 schrieb Antonio:

**Comment by hroest** [comment]
is this still an ongoing issue @cbielow @sagitter
