### ISSUE TITLE
pyOpenMS build errors

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2246]
I tried to build pyOpenMS from the current "develop" branch on Mac OS X. It failed with the following error:

```
Error compiling Cython file:
------------------------------------------------------------
...
    
    cdef cppclass SpectrumAccessQuadMZTransforming(SpectrumAccessTransforming) :
        # wrap-inherits:
        #  SpectrumAccessTransforming

        SpectrumAccessQuadMZTransforming() nogil except + # wrap-pass-constructor
                                        ^
------------------------------------------------------------

/Users/hw5/Software/OpenMS/src/pyOpenMS/pxds/SpectrumAccessQuadMZTransforming.pxd:14:41: no matching function for call to SpectrumAccessTransforming::SpectrumAccessTransforming()

Error compiling Cython file:
------------------------------------------------------------
...
cdef extern from "<OpenMS/METADATA/Modification.h>" namespace "OpenMS":
    
    cdef cppclass Modification(SampleTreatment) :
        # wrap-inherits:
        #  SampleTreatment
        Modification() nogil except +
                    ^
------------------------------------------------------------

/Users/hw5/Software/OpenMS/src/pyOpenMS/pxds/Modification.pxd:10:21: no matching function for call to SampleTreatment::SampleTreatment()
```

I think the parameter-less constructors that pyOpenMS tries to wrap don't exist for those classes.

**Comment by hroest** [comment]
@hendrikweisser which version of autowrap and Cython are you using?

**Comment by hendrikweisser** [comment]
autowrap 0.8.0 and Cython 0.21. I see now that CMake told me "should be 0.23 or higher" for Cython, but didn't give an error. Also, verson 0.21 was what got installed automatically with autowrap from PyPI. Anyway, I've just updated Cython to 0.24 and will try again.

**Comment by hendrikweisser** [comment]
Okay, after the update I got it to build. I had to make manual changes related to issues #1777 (still!) and #2139, though, i.e. delete the "QtCore" and "QtNetwork" files and put absolute paths in the dynamic libraries.

I get some test failures from "run_nose.py", but I assume they're not related to the build process:
```
======================================================================
ERROR: test_readfile (unittests.test_FileIO.TestPepXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hw5/Software/OpenMS/build/pyOpenMS/tests/unittests/test_FileIO.py", line 17, in test_readfile
    pepxml_file.load(self.filename, prots, peps)
  File "pyopenms/pyopenms.pyx", line 60377, in pyopenms.pyopenms.PepXMLFile.load (pyopenms/pyopenms.cpp:1187597)
    return self._load_0(*args)
  File "pyopenms/pyopenms.pyx", line 60221, in pyopenms.pyopenms.PepXMLFile._load_0 (pyopenms/pyopenms.cpp:1183684)
    self.inst.get().load(deref(cs_filename), deref(v1), deref(v2))
RuntimeError: the element 'Enzyme name cannot be found. '' could not be found

======================================================================
ERROR: test_readfile_content (unittests.test_FileIO.TestPepXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hw5/Software/OpenMS/build/pyOpenMS/tests/unittests/test_FileIO.py", line 24, in test_readfile_content
    pepxml_file.load(self.filename, prots, peps)
  File "pyopenms/pyopenms.pyx", line 60377, in pyopenms.pyopenms.PepXMLFile.load (pyopenms/pyopenms.cpp:1187597)
    return self._load_0(*args)
  File "pyopenms/pyopenms.pyx", line 60221, in pyopenms.pyopenms.PepXMLFile._load_0 (pyopenms/pyopenms.cpp:1183684)
    self.inst.get().load(deref(cs_filename), deref(v1), deref(v2))
RuntimeError: the element 'Enzyme name cannot be found. '' could not be found

----------------------------------------------------------------------
```

I think this can be closed.

**Comment by hroest** [comment]
@hendrikweisser I figured out your error: 2321 it was a lot of *FUN* to track that one down :-)
