### ISSUE TITLE
TOPPView crash idXML if clicked on scan view

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2922]
To reproduce:
- open idXML
- in scan view, double click on "No peak map" crashes TOPPView

**Comment by hroest** [comment]
(non-debug) backtrace

```
(gdb) bt
#0  0x00007ffff7a34f8d in OpenMS::LayerData::getPeakData() const () from /home/hr/openmsall/builds/openms/lib/libOpenMS_GUI.so
#1  0x00007ffff7a704f2 in OpenMS::Spectrum1DCanvas::activateSpectrum(unsigned long, bool) () from /home/hr/openmsall/builds/openms/lib/libOpenMS_GUI.so
#2  0x00007ffff7b05d47 in OpenMS::TOPPViewSpectraViewBehavior::showSpectrumAs1D(int) () from /home/hr/openmsall/builds/openms/lib/libOpenMS_GUI.so
#3  0x00007ffff799acf0 in OpenMS::TOPPViewBase::showSpectrumAs1D(int) () from /home/hr/openmsall/builds/openms/lib/libOpenMS_GUI.so
#4  0x00007ffff7b12981 in OpenMS::TOPPViewBase::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () from /home/hr/openmsall/builds/openms/lib/libOpenMS_GUI.so
#5  0x00007ffff5a7fd2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff7b0c0b1 in OpenMS::SpectraViewWidget::spectrumDoubleClicked(int) () from /home/hr/openmsall/builds/openms/lib/libOpenMS_GUI.so
#7  0x00007ffff7a6336a in OpenMS::SpectraViewWidget::spectrumDoubleClicked_(QTreeWidgetItem*) () from /home/hr/openmsall/builds/openms/lib/libOpenMS_GUI.so
#8  0x00007ffff7b0f5dc in OpenMS::SpectraViewWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () from /home/hr/openmsall/builds/openms/lib/libOpenMS_GUI.so
#9  0x00007ffff5a7fd2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff6612260 in QTreeWidget::itemDoubleClicked(QTreeWidgetItem*, int) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff5a7fd2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff659c845 in QAbstractItemView::doubleClicked(QModelIndex const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff65e7fca in QTreeView::mouseDoubleClickEvent(QMouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff63873c7 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff6485b8e in QFrame::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff65ab6db in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff65ea20c in QTreeView::viewportEvent(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff5a51172 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff634403c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff6349c19 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff79d40a9 in OpenMS::QApplicationTOPP::notify(QObject*, QEvent*) () from /home/hr/openmsall/builds/openms/lib/libOpenMS_GUI.so
#22 0x00007ffff5a5138b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff6348b32 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff63a15bb in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff63a3b7b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff634405c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff6349516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff79d40a9 in OpenMS::QApplicationTOPP::notify(QObject*, QEvent*) () from /home/hr/openmsall/builds/openms/lib/libOpenMS_GUI.so
#29 0x00007ffff5a5138b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff5d93848 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#31 0x00007ffff5d951a5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#32 0x00007ffff5d78f08 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#33 0x00007fffead64200 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#34 0x00007ffff1dd6197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff1dd63f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff1dd649c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff5aa77cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007ffff5a4eb4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00007ffff5a56bec in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x0000000000402e14 in main ()
```
