### ISSUE TITLE
TOPPView segfaults

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3230]
when closing a tab by double-clicking it, then clicking on Windows -> tile vertical, a "ghost" window appears. 
![screenshot from 2018-02-06 17-38-13](https://user-images.githubusercontent.com/464014/35888100-8f86041e-0b64-11e8-8ebc-94dda70f6c14.png)

when trying to close that "ghost" window, TOPPView segfaults at `OpenMS::TOPPViewBase::updateTabBar`

**Comment by hroest** [comment]
looks like the error is in 
```
(gdb) bt
#0  0x00007ffff78a8e52 in OpenMS::TOPPViewBase::updateTabBar (this=0x8f0670, w=0x14a8e80) at /home/hr/openmsall/source/OpenMS_qt5/src/openms_gui/source/VISUAL/APPLICATIONS/TOPPViewBase.cpp:2203
#1  0x00007ffff7a7b573 in OpenMS::TOPPViewBase::qt_static_metacall (_o=0x8f0670, _c=QMetaObject::InvokeMetaMethod, _id=19, _a=0x7fffffffc0c0) at /home/hr/openmsall/builds/openms_qt5_2/src/openms_gui/moc_TOPPViewBase.cpp:351
#2  0x00007ffff418fd2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff4bb5a2f in QMdiArea::subWindowActivated(QMdiSubWindow*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff4bbcb3c in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff4bbcc9b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff4bbcf05 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff418fd2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff4bc1476 in QMdiSubWindow::windowStateChanged(QFlags<Qt::WindowState>, QFlags<Qt::WindowState>) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff4bca612 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff4bcbaa7 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff418fd2a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff4a4edb8 in QApplication::focusChanged(QWidget*, QWidget*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff4a570a7 in QApplicationPrivate::setFocusWidget(QWidget*, Qt::FocusReason) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff4a9172d in QWidget::setFocus(Qt::FocusReason) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff4a509cc in QApplicationPrivate::giveFocusAccordingToFocusPolicy(QWidget*, QEvent*, QPoint) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff4a5b431 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff78e607c in OpenMS::QApplicationTOPP::notify (this=0x7fffffffd490, rec=0x14a8e80, ev=0x7fffffffcad0) at /home/hr/openmsall/source/OpenMS_qt5/src/openms_gui/source/VISUAL/APPLICATIONS/MISC/QApplicationTOPP.cpp:99
#18 0x00007ffff416138b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff4a58b32 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff4ab15bb in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff4ab3b7b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff4a5405c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff4a59516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff78e607c in OpenMS::QApplicationTOPP::notify (this=0x7fffffffd490, rec=0x911e00, ev=0x7fffffffd000) at /home/hr/openmsall/source/OpenMS_qt5/src/openms_gui/source/VISUAL/APPLICATIONS/MISC/QApplicationTOPP.cpp:99
#25 0x00007ffff416138b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff44a34e1 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007ffff44a51a5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#28 0x00007ffff4488f08 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#29 0x00007fffecfe1200 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#30 0x00007ffff21e5197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff21e53f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ffff21e549c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff41b77cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff415eb4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007ffff4166bec in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x0000000000403c93 in main (argc=3, argv=0x7fffffffdad8) at /home/hr/openmsall/source/OpenMS_qt5/src/openms_gui/source/VISUAL/APPLICATIONS/GUITOOLS/TOPPView.cpp:181
(gdb) 
```

seems to happen here ` Int window_id = tbw->getWindowId();` -- sorry I dont quite know how to debug signals in qt

**Comment by timosachsenberg** [comment]
fixed in: https://github.com/OpenMS/OpenMS/pull/3196/commits/5e981b156db45d8593c00ac0f799e61ec157c871
Problem was, that the child widget was closed but not the parent window.
