### ISSUE TITLE
MSGFPlusAdapter error message for empty fasta input

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#3442]
I got the following error

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.getByteAt(CompactFastaSequence.java:163)
	at edu.ucsd.msjava.msdbsearch.CompactSuffixArray.createSuffixArrayFiles(CompactSuffixArray.java:280)
	at edu.ucsd.msjava.msdbsearch.CompactSuffixArray.(CompactSuffixArray.java:69)
	at edu.ucsd.msjava.msdbsearch.CompactSuffixArray.(CompactSuffixArray.java:89)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:207)
	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:105)
	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:56)
```

which seems to be caused by an empty fasta input file. Would it be possible to create a meaningful error message in this case?

**Comment by timosachsenberg** [comment]
Hi,
Thanks for reporting.
I think best would be to report this to MSGFPlus https://github.com/MSGFPlus/msgfplus
They could catch the exception and output a meaningful error message.
