### ISSUE TITLE
TOPPView crashes if table is exported from identification view 

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3590]
When I try to export the annotated mzml table from ToppView it crashes.

Timo: can reproduce (Open BSA1.mzML, Annotate with Identifications, Export table)

**Comment by timosachsenberg** [comment]
```
#0  0x00007ffff7986c18 in QTableWidgetItem::text (this=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtablewidget.h:97
#1  0x00007ffff7985059 in OpenMS::SpectraIdentificationViewWidget::exportEntries_ (this=0xb19450) at /media/sachsenb/BACKUP/OpenMS/src/openms_gui/source/VISUAL/SpectraIdentificationViewWidget.cpp:813
```

Seems to be a problem with the scan type column (the item is empty... will check later)
dissociation = Collision-induced dissociation
scan type = ???
zoom = no
```

MS | index | RT | precursor m/z | dissociation | scan type | zoom | score
-- | -- | -- | -- | -- | -- | -- | --
2 | 50 | 1554.4921875 | 358.17468261718801 | Collision-induced dissociation | no | 0 | 0
2 | 101 | 1607.2958984375 | 368.83215332031199 | Collision-induced dissociation | no | 0.045454545454545497 | 0

```
