### ISSUE TITLE
Build pyOpenMS with static QT to avoid version mismatches with e.g. Spyder/pyQT (especially on Win)

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#4291]
On windows I get an error message indicating some problems with the shared libraries.
Potentially, because of different Qt versions used by pyopenms and the plotting library.

On the other hand: I see no pyopenms.so (as indicated below) on windows.
Instead I see quite some cython files 
![image](https://user-images.githubusercontent.com/5803621/66552914-7f751e80-eb4a-11e9-8475-f9fadddb060a.png)

So I wondered if this indicates an installation error...

On the other hand I can run some pyOpenMS scripts if I don't use the plotting library.

```
E:\pyOpenMS-examples\pyopenms-extra\src\specViewer>python SpecViewer.py


======================================================================


maybe you miss some libraries. please run ldd (on linux) or
dependency walker (on windows) on


C:\Users\sachs\AppData\Local\Programs\Python\Python37\lib\site-packages\pyopenms\pyopenms.so


======================================================================


Traceback (most recent call last):
  File "SpecViewer.py", line 18, in <module>
    import pyopenms as pms
  File "C:\Users\sachs\AppData\Local\Programs\Python\Python37\lib\site-packages\pyopenms\__init__.py", line 75, in <module>
    raise e
  File "C:\Users\sachs\AppData\Local\Programs\Python\Python37\lib\site-packages\pyopenms\__init__.py", line 45, in <module>
    from .all_modules import *
  File "C:\Users\sachs\AppData\Local\Programs\Python\Python37\lib\site-packages\pyopenms\all_modules.py", line 1, in <module>
    from .pyopenms_1 import *
ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.
```

**Comment by timosachsenberg** [comment]
- on linux I don't have this problem

**Comment by jpfeuffer** [comment]
Can you run dependency walker on the pyd modules?

**Comment by jpfeuffer** [comment]
From where is pyOpenMS installed? Or Self compiled?

**Comment by timosachsenberg** [comment]
Installed via pip

**Comment by timosachsenberg** [comment]
![image](https://user-images.githubusercontent.com/5803621/66563269-bb65af00-eb5d-11e9-920b-8999494ad56f.png)

**Comment by jpfeuffer** [comment]
Ah no, does not look good I think. It uses the QT from your Python environment.

**Comment by timosachsenberg** [comment]
If I change the order between PyQt5 and pyopenms so that pyopenms is first loaded
I get the error:
```
Traceback (most recent call last):
  File "SpecViewer.py", line 3, in <module>
    from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, \
ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.
```
in the next line of code

**Comment by timosachsenberg** [comment]
Interestingly, there is a related issue on StackOverflow
https://stackoverflow.com/questions/55875548/pyopenms-dll-load-failed-the-specified-procedure-could-not-be-found

**Comment by timosachsenberg** [comment]
Ok I found a crappy solution. If I copy all DLLs from PyQt5 to the pyopenms site-package folder I get it to run

**Comment by jpfeuffer** [comment]
Can you check if it is enough to have QtCore and Network?
To see if it is a version problem or a completely missing DLL

**Comment by timosachsenberg** [comment]
seems to be enough to use the new 5.13-ish QtCore and Network version

**Comment by hroest** [comment]
I had the same issue when trying to get pyopenms to run in Spyder: https://github.com/spyder-ide/spyder/issues/9227

**Comment by hroest** [comment]
On Linux we have audithweel but it seems on Windows that does not exist: https://discuss.python.org/t/packaging-dlls-on-windows/1401/3

**Comment by hroest** [comment]
the other approach of course would be to link Qt statically, at least for pyOpenMS builds 

@cbielow @jpfeuffer is our build system set up to do that?

**Comment by cbielow** [comment]
statically linking Qt is troublesome due to its LGPL license (https://forum.qt.io/topic/84051/distribution-with-lgpl/2)

**Comment by hroest** [comment]
> statically linking Qt is troublesome due to its LGPL license (https://forum.qt.io/topic/84051/distribution-with-lgpl/2)

this would only be for the Python package -- also you are allowed to take BSD code (OpenMS) and re-distribute it as LGPL / GPL code, see https://opensource.stackexchange.com/questions/304/can-i-take-bsd-licensed-code-and-distribute-it-under-gpl so I dont really see the problem with that?

**Comment by StefanBruens** [comment]
Statically linking does not solve the problem, but introduces new ones.

If you load different versions of the same library, you are putting yourself into trouble, as *internal* library symbols with possibly incompatible implementation may end up in the address space of a single implementation.

Fortunately, Qt guarantees strong backwards compatibility between minor version (e.g. you can replace Qt 5.12.x with Qt 5.15.x, but not vice versa). So you just have to make sure you don't accidentally provide multiple Qt versions. Unfortunately, this is somewhat difficult on Windows, as you don't have a proper package manager, and every Python Wheel just bundles its own private version.

**Comment by ShapanGG** [comment]
Commenting just incase anybody else has issues in the future. 

"PyOpenMs loads Qt even when no GUI is being used. And if another Qt is loaded before PyOpenMs, then this causes it to fail."
^ This is the cause of the issue

I didn't have any luck circumventing the issue by moving the DLLs, but i was able to get my program to work, but following the above comment and just reverting to PyQt5.12; pyopenms ships with 5.12.6.
