### ISSUE TITLE
Fails: conda create -n openms -c bioconda openms

### ISSUE THREAD

**Issue by soerendip** [OpenMS/OpenMS#5156]
Apparently openms cannot be installed anymore with anaconda:

```
conda create -n openms -c bioconda openms
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:
```

No `openms` environment exists. I would expect this command to install `openms` with the correct dependencies. 
I am not sure if this is the right channel to report this error.

**Comment by jpfeuffer** [comment]
Hi! Yes, thanks for reporting. Do you have the subsequent lines of the Unsatisfiable error?
Can you also try to add conda-forge to the channels as well?
Maybe also choose a fixed, older python version. Not sure for which pythons the package was built yet.

**Comment by soerendip** [comment]
I tried python 2.7, 3.5 and others. As reported in the requirements. Nothing worked actually. It worked before though. 

```
conda install -c bioconda openms -v
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working...
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/home/swacker/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 818, in _run_sat
    should_retry_solve=ssc.should_retry_solve
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 1320, in solve
    raise UnsatisfiableError({})
conda.exceptions.UnsatisfiableError:
Did not find conflicting dependencies. If you would like to know which
packages conflict ensure that you have enabled unsatisfiable hints.

conda config --set unsatisfiable_hints True


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 308, in install
    raise e
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 299, in install
    should_retry_solve=(repodata_fn != repodata_fns[-1]),
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 704, in _add_specs
    ssc.r.find_conflicts(spec_set)
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 352, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

```

I will try removing miniconda.

**Comment by soerendip** [comment]
I tried removing miniconda and install everything from scratch. Same error. 
Also tried python 2.7, 3.5, 3.4, 3.3. And also adding the `conda-forge` channel.

**Comment by soerendip** [comment]
`conda install -c bioconda openms=2.5` worked.

**Comment by jpfeuffer** [comment]
Hmm I tried it today and could not reproduce:
`./bin/conda create -n openms_test -c bioconda -c conda-forge openms``
worked on macOS at least. I can try later on a linux.
