### ISSUE TITLE
Q: pyopenms wrapping - complex structure - no converter error

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#5216]
Hi everyone, 

I have a wrapping issue and not sure how to solve it:

example code: 
```
from Types cimport *
from libcpp.vector cimport vector as libcpp_vector
from libcpp.unordered_map cimport unordered_map as libcpp_unordered_map

cdef cppclass MetaboTargetedAssay "OpenMS::MetaboTargetedAssay":

       MetaboTargetedAssay() nogil except +
       MetaboTargetedAssay(MetaboTargetedAssay) nogil except + #wrap-ignore

libcpp_unordered_map[ UInt64, libcpp_vector[ MetaboTargetedAssay ] ] buildAmbiguityGroup(
                             libcpp_vector[ MetaboTargetedAssay]& v_mta,
                             double& ar_mz_tol,
                             double& ar_rt_tol,
                             String& ar_mz_tol_unit_res,
                             size_t in_files_size) nogil except +
```
Actual file with commented code to make it compile/wrappable (ps: I fixed all the errors regarding style locally):
https://github.com/OpenMS/OpenMS/blob/8560d0aa02c1271453ed9bcac8397b2064c82e5d/src/pyOpenMS/pxds/MetaboTargetedAssay.pxd

Error:
```
Traceback (most recent call last):
  File "/Users/alka/Documents/work/software/openms_oa_1/pyopenms_build/pyOpenMS/create_cpp_extension.py", line 208, in <module>
    autowrap_include_dirs = doCythonCodeGeneration(modname, allDecl_mapping, instance_map, converters)
  File "/Users/alka/Documents/work/software/openms_oa_1/pyopenms_build/pyOpenMS/create_cpp_extension.py", line 168, in doCythonCodeGeneration
    autowrap_include_dirs = autowrap.generate_code(allDecl_mapping[modname]["decls"], instance_map,
  File "/usr/local/miniconda3/envs/build_pyopenms_39/lib/python3.9/site-packages/autowrap/__init__.py", line 66, in generate_code
    gen.create_pyx_file(debug)
  File "/usr/local/miniconda3/envs/build_pyopenms_39/lib/python3.9/site-packages/autowrap/CodeGenerator.py", line 216, in create_pyx_file
    create_for(ResolvedClass, self.create_wrapper_for_class)
  File "/usr/local/miniconda3/envs/build_pyopenms_39/lib/python3.9/site-packages/autowrap/CodeGenerator.py", line 212, in create_for
    method(resolved)
  File "/usr/local/miniconda3/envs/build_pyopenms_39/lib/python3.9/site-packages/autowrap/CodeGenerator.py", line 471, in create_wrapper_for_class
    codes = self.create_wrapper_for_method(r_class, name, methods)
  File "/usr/local/miniconda3/envs/build_pyopenms_39/lib/python3.9/site-packages/autowrap/CodeGenerator.py", line 622, in create_wrapper_for_method
    code = self.create_wrapper_for_nonoverloaded_method(cdcl, py_name, methods[0])
  File "/usr/local/miniconda3/envs/build_pyopenms_39/lib/python3.9/site-packages/autowrap/CodeGenerator.py", line 793, in create_wrapper_for_nonoverloaded_method
    out_converter = self.cr.get(res_t)
  File "/usr/local/miniconda3/envs/build_pyopenms_39/lib/python3.9/site-packages/autowrap/ConversionProvider.py", line 117, in get
    raise Exception("no converter for %s" % cpp_type)
Exception: no converter for libcpp_unordered_map[unsigned long int,metabo_vector]
```

With the guidance of Sam I tried to wrap the "complex" code libcpp_vector[ MetaboTargetedAssay] as "wrap-instances".

```
# wrap-instances:
   #  metabo_vector := libcpp_vector[MetaboTargetedAssay]

    libcpp_unordered_map[ UInt64, metabo_vector ] buildAmbiguityGroup(libcpp_vector[ MetaboTargetedAssay]& v_mta,
                                                                                               double& ar_mz_tol,
                                                                                               double& ar_rt_tol,
                                                                                               String& ar_mz_tol_unit_res,
                                                                                               size_t in_files_size) nogil except +
```

Unfortunately leading to an additional error. 
```
Error compiling Cython file:
------------------------------------------------------------
...
       libcpp_vector[ MetaboTargetedAssay_CompoundTargetDecoyPair ] pairCompoundWithAnnotatedSpectra(libcpp_vector[ SiriusMSFile_CompoundInfo ]& v_cmpinfo,
                                                                                                     libcpp_vector[ SiriusFragmentAnnotation_SiriusTargetDecoySpectra]& annotated_spectra) nogil except +
       # wrap-instances:
       #  metabo_vector := libcpp_vector[MetaboTargetedAssay]

       libcpp_unordered_map[ UInt64, metabo_vector ] buildAmbiguityGroup(libcpp_vector[ MetaboTargetedAssay]& v_mta,
                                                  ^
------------------------------------------------------------

/Users/alka/Documents/work/software/openms_oa_1/OpenMS/src/pyOpenMS/pxds/MetaboTargetedAssay.pxd:40:51: unknown type in template argument
```

Does anyone have experience which such behaviour?

**Comment by jpfeuffer** [comment]
There is no autowrap conversion for unordered_maps yet:
https://github.com/uweschmitt/autowrap/blob/master/autowrap/ConversionProvider.py#L630

I assume the code can be pretty much copied though?

**Comment by oliveralka** [comment]
Thanks, I will take a look!

**Comment by jpfeuffer** [comment]
Done! Autowrap supports unordered map and other new containers now.
