### ISSUE TITLE
pyOpenMS binder FeatureFinderAlgorithmMetaboIdent() param issues

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5649]
FeatureFinderAlgorithmMetaboIdent() fails to complete the run() method with default parameters. In fact, the only way it can complete the operation is by changing the "type of elution model to fit to features" to "**none**" (symmetric or assymetric models do not work). The error produced is the following:

```
pyopenms/pyopenms_4.pyx in pyopenms.pyopenms_4.FeatureFinderAlgorithmMetaboIdent.run()

RuntimeError: the range of the operation was invalid
```

**Comment by timosachsenberg** [comment]
Hi @eeko-kon do you have the compound text file and the spectra? I can try to debug that

**Comment by timosachsenberg** [comment]
```
Starting program: /home/sachsenb/OMS/OpenMS/openms-build/bin/FeatureFinderMetaboIdent -id epemicins.tsv -in MapAligned_20210827_UMETAB219_POS_DNPM_Plate-2_MDNAWGS14_blank.mzML -out test.featureXML -extract:mz_window 5.0 -detect:peak_width 20.0
0 features left after selection of best candidates.
No overlaps between features found.

Catchpoint 1 (exception thrown), 0x00007ffff5b77d1d in cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff5b77d1d in cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff752cd4c in double OpenMS::Math::median<gnu_cxx::normal_iterator<double, std::vector<double, std::allocator<double> > > >(gnu_cxx::normal_iterator<double, std::vector<double, std::allocator<double> > >, gnu_cxx::normal_iterator<double*, std::vector<double, std::allocator<double> > >, bool) [clone .constprop.620] ()
   from /home/sachsenb/OMS/OpenMS/openms-build/lib/libOpenMS.so
#2  0x00007ffff738e90d in OpenMS::ElutionModelFitter::fitElutionModels(OpenMS::FeatureMap&) () from /home/sachsenb/OMS/OpenMS/openms-build/lib/libOpenMS.so
```

**Comment by timosachsenberg** [comment]
so probably some issue with the blank and no features detected?
could be a bug in FFmetaboident or one of the algorithms it calls

**Comment by jpfeuffer** [comment]
@timosachsenberg Besides that: Why does python print "the range of the operation was invalid"?

**Comment by timosachsenberg** [comment]
It is the C++ exception printed in python. Probably because of accessing an empty vector or similar.

**Comment by timosachsenberg** [comment]
Ok I found a fix. PR linked.

**Comment by eeko-kon** [comment]
Amazing, thank you!
