### ISSUE TITLE
SiriusAdapter issue related to OpenMS + snakemake in Linux only

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5785]
I have this very strange error that only comes up in a Linux system, while using snakemake:

```
FATAL: External invocation of Sirius failed. Standard output and error were:

Jan 25, 2022 12:01:47 PM org.apache.commons.beanutils.FluentPropertyBeanIntrospector introspect
INFO: Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
INFO    12:01:49 - Sirius Workspace Successfull initialized at: /home/azureuser/.sirius-4.9
INFO    12:01:49 - You run SIRIUS 4.9.12
INFO    12:01:49 - Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v9.1.1, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO    12:01:49 - Treebuilder priorities loaded from 'sirius.properties' are: [GUROBI, CPLEX, CLP, GLPK]
INFO    12:01:49 - CPU check done. 4 cores that handle 8 threads were found.
INFO    12:01:50 - Bug reporter initialized.
INFO    12:01:50 - Web API initialized.
INFO    12:01:51 - Running with following arguments: [--processors=8, --input, /tmp/20220125_120133_metabotest2_16768_2.ms, --project, /tmp/20220125_120133_metabotest2_16768_1/sirius_out, sirius, --db=none, --ppm-max=10.0, --ppm-max-ms2=10.0, --compound-timeout=100, --tree-timeout=0, --ions-considered=[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+, --profile=orbitrap, --elements-enforced=CHN[15]O[40]S[4], --candidates=5]
FINE    12:01:51 - <0>[InputExpanderJJob] Running post processing
FINE    12:01:51 - <0>[InputExpanderJJob] Running cleanup
INFO    12:01:51 - <1>[InputExpanderJJob] Expanding Input Files: '/tmp/20220125_120133_metabotest2_16768_2.ms'...
INFO    12:01:51 - <1>[InputExpanderJJob] ...Input Files successfully expanded!
FINE    12:01:51 - <1>[InputExpanderJJob] Running post processing
FINE    12:01:51 - <1>[InputExpanderJJob] Running cleanup
WARNING 12:03:41 - Could not load GrbSolver! Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v9.1.1, CPLEX-v12.7.1, COIN-OR-v1.17.3: gurobi/GRBException
WARNING 12:03:41 - Could not load CPLEXSolver! Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v9.1.1, CPLEX-v12.7.1, COIN-OR-v1.17.3: ilog/concert/IloNumVar
WARNING 12:06:39 - <7801>[SiriusSubToolJob | 659_20220125_120133_metabotest2_16768_2__4532477635505084859-2215--2214--UNKNOWN@932m/z] ToolChain Job canceled due to: de.unijena.bioinf.jjobs.exceptions.TimeoutException: Timeout reached!
WARNING 12:06:41 - <10012>[SiriusSubToolJob | 629_20220125_120133_metabotest2_16768_2__13393815486500953430-2131--2130--UNKNOWN@1180m/z] ToolChain Job canceled due to: de.unijena.bioinf.jjobs.exceptions.TimeoutException: Timeout reached!
WARNING 12:07:16 - <14348>[SiriusSubToolJob | 715_20220125_120133_metabotest2_16768_2__775629592185648081-2335--2334--UNKNOWN@963m/z] ToolChain Job canceled due to: de.unijena.bioinf.jjobs.exceptions.TimeoutException: Timeout reached!
de.unijena.bioinf.jjobs.exceptions.TimeoutException: Timeout reached!
        at de.unijena.bioinf.jjobs.TimeLimit.checkTimeOut(TimeLimit.java:32)
        at de.unijena.bioinf.jjobs.BasicJJob.checkForInterruption(BasicJJob.java:101)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance.checkHeuristicInterruption(FasterTreeComputationInstance.java:412)
        at de.unijena.bioinf.FragmentationTreeConstruction.ftheuristics.CriticalPathInsertionHeuristic.solve(CriticalPathInsertionHeuristic.java:137)
        at de.unijena.bioinf.FragmentationTreeConstruction.ftheuristics.treebuilder.ExtendedCriticalPathHeuristicTreeBuilder.computeTree(ExtendedCriticalPathHeuristicTreeBuilder.java:60)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.tree.TreeBuilder$FluentInterface.solve(TreeBuilder.java:100)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance.recalibrate(FasterTreeComputationInstance.java:558)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance$RecalibrationJob.compute(FasterTreeComputationInstance.java:537)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance$RecalibrationJob.compute(FasterTreeComputationInstance.java:523)
        at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:120)
        at de.unijena.bioinf.jjobs.BasicMasterJJob$1.compute(BasicMasterJJob.java:87)
        at java.base/java.util.concurrent.RecursiveTask.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doJoin(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.join(Unknown Source)
        at de.unijena.bioinf.jjobs.BasicJJob.awaitResult(BasicJJob.java:208)
        at de.unijena.bioinf.jjobs.JJob.takeResult(JJob.java:250)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance.estimateTreeSizeAndRecalibration(FasterTreeComputationInstance.java:303)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance.compute(FasterTreeComputationInstance.java:172)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance.compute(FasterTreeComputationInstance.java:55)
        at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:120)
        at de.unijena.bioinf.jjobs.BasicMasterJJob$1.compute(BasicMasterJJob.java:87)
        at java.base/java.util.concurrent.RecursiveTask.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doJoin(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.join(Unknown Source)
        at de.unijena.bioinf.jjobs.BasicJJob.awaitResult(BasicJJob.java:208)
        at de.unijena.bioinf.sirius.Sirius$SiriusIdentificationJob.compute(Sirius.java:627)
        at de.unijena.bioinf.sirius.Sirius$SiriusIdentificationJob.compute(Sirius.java:610)
        at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:120)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
WARNING 12:08:13 - <20715>[SiriusSubToolJob | 1418_20220125_120133_metabotest2_16768_2__10424745578085788013-4893--4892--UNKNOWN@706m/z] ToolChain Job canceled due to: de.unijena.bioinf.jjobs.exceptions.TimeoutException: Timeout reached!
WARNING 12:09:13 - <20966>[SiriusSubToolJob | 830_20220125_120133_metabotest2_16768_2__3489275990606049943-2603--2602--UNKNOWN@1074m/z] ToolChain Job canceled due to: de.unijena.bioinf.jjobs.exceptions.TimeoutException: Timeout reached!
WARNING 12:09:54 - <23449>[SiriusSubToolJob | 794_20220125_120133_metabotest2_16768_2__7241766039985843311-2511--2510--UNKNOWN@960m/z] ToolChain Job canceled due to: de.unijena.bioinf.jjobs.exceptions.TimeoutException: Timeout reached!
de.unijena.bioinf.jjobs.exceptions.TimeoutException: Timeout reached!
        at de.unijena.bioinf.jjobs.TimeLimit.checkTimeOut(TimeLimit.java:32)
        at de.unijena.bioinf.jjobs.BasicJJob.checkForInterruption(BasicJJob.java:101)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance.checkHeuristicInterruption(FasterTreeComputationInstance.java:412)
        at de.unijena.bioinf.FragmentationTreeConstruction.ftheuristics.CriticalPathInsertionHeuristic.solve(CriticalPathInsertionHeuristic.java:137)
        at de.unijena.bioinf.FragmentationTreeConstruction.ftheuristics.treebuilder.ExtendedCriticalPathHeuristicTreeBuilder.computeTree(ExtendedCriticalPathHeuristicTreeBuilder.java:60)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.tree.TreeBuilder$FluentInterface.solve(TreeBuilder.java:100)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance$TreeComputationJob.compute(FasterTreeComputationInstance.java:485)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance$TreeComputationJob.compute(FasterTreeComputationInstance.java:468)
        at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:120)
        at de.unijena.bioinf.jjobs.BatchJJob.compute(BatchJJob.java:28)
        at de.unijena.bioinf.jjobs.BatchJJob.compute(BatchJJob.java:9)
        at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:120)
        at de.unijena.bioinf.jjobs.BasicMasterJJob$1.compute(BasicMasterJJob.java:87)
        at java.base/java.util.concurrent.RecursiveTask.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doJoin(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.join(Unknown Source)
        at de.unijena.bioinf.jjobs.BasicJJob.awaitResult(BasicJJob.java:208)
        at de.unijena.bioinf.jjobs.JJob.takeResult(JJob.java:250)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance.estimateTreeSizeAndRecalibration(FasterTreeComputationInstance.java:241)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance.compute(FasterTreeComputationInstance.java:172)
        at de.unijena.bioinf.FragmentationTreeConstruction.computation.FasterTreeComputationInstance.compute(FasterTreeComputationInstance.java:55)
        at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:120)
        at de.unijena.bioinf.jjobs.BasicMasterJJob$1.compute(BasicMasterJJob.java:87)
        at java.base/java.util.concurrent.RecursiveTask.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doJoin(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.join(Unknown Source)
        at de.unijena.bioinf.jjobs.BasicJJob.awaitResult(BasicJJob.java:208)
        at de.unijena.bioinf.sirius.Sirius$SiriusIdentificationJob.compute(Sirius.java:627)
        at de.unijena.bioinf.sirius.Sirius$SiriusIdentificationJob.compute(Sirius.java:610)
        at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:120)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
WARNING 12:09:56 - <23852>[SiriusSubToolJob | 727_20220125_120133_metabotest2_16768_2__12074164701845916177-2368--2367--UNKNOWN@756m/z] ToolChain Job canceled due to: de.unijena.bioinf.jjobs.exceptions.TimeoutException: Timeout reached!

9
SiriusAdapterAlgorithm.cpp(383): Deleting temporary directory /tmp/20220125_120133_metabotest2_16768_1. Set debug level to 9 or higher to keep it.
SiriusAdapterAlgorithm.cpp(388): Deleting temporary msfile /tmp/20220125_120133_metabotest2_16768_2.ms. Set debug level to 9 or higher to keep it.
Error: Unexpected internal error (the value '' was used but is not valid; FATAL: SIRIUS could not be executed!)
Error occurred in line 591 of file /home/jenkins/ws/openms/RC/openms_release_packaging/a9154670/source/src/openms/source/ANALYSIS/ID/SiriusAdapterAlgorithm.cpp (in function: const std::vector<OpenMS::String> OpenMS::SiriusAdapterAlgorithm::callSiriusQProcess(const OpenMS::String&, const OpenMS::String&, OpenMS::String&, const OpenMS::String&, bool) const) !
```

Somehow there is an issue with callSiriusQProcess - any thoughts? I could get a MacOS VM and run everything there but there seems to be a weird bug here. This is unrelated to SIRIUS, since I tried to run the files that are failing directly using the executable and it works perfectly fine.

**Comment by eeko-kon** [comment]
And it is also not produced when using SiriusAdapter CLI without snakemake

**Comment by jpfeuffer** [comment]
Exit Code 9 usually means the underlying process was killed. If you didn't do it yourself, it was probably the operating system, most likely because of running out of RAM or something like this.

**Comment by eeko-kon** [comment]
This is interesting. I have a VM with 128GB memory. How is that possible? But you are right- the process uses all the memory before it breaks.
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                          
 6258 azureus+  20   0  115.8g  26.8g  20800 S 206.0  21.3  43:02.47 java                             
  18199 azureus+  20   0  115.8g  16.0g  22040 S 204.7  12.7  30:13.92 java                             
   6032 azureus+  20   0  115.9g  16.4g  19484 S 204.3  13.1  42:17.33 java                             
   7718 azureus+  20   0  115.9g  14.4g  21076 S 203.0  11.4  41:26.10 java                             
  11276 azureus+  20   0  115.8g  11.8g  20924 S 201.7   9.4  40:06.20 java                             
   5050 azureus+  20   0  115.9g  14.2g  20428 S 199.3  11.3  42:59.58 java                             
   5401 azureus+  20   0  115.9g  17.4g  19852 S 111.0  13.8  41:47.09 java       
```

**Comment by jpfeuffer** [comment]
Is this using containers? I am not sure what the default is but can you set a reasonable java_max_memory or how that parameter is called?

**Comment by eeko-kon** [comment]
"Dealing with very large workflows"
If your workflow has a lot of jobs, Snakemake might need some time to infer the dependencies (the job DAG) and which jobs are actually required to run. The major bottleneck involved is the filesystem, which has to be queried for existence and modification dates of files. To overcome this issue, Snakemake allows to run large workflows in batches. This way, fewer files have to be evaluated at once, and therefore the job DAG can be inferred faster. By running

`$ snakemake --cores 4 --batch myrule=1/3`

I used this initially but even though it seems like the process is running, and going to the next one, the final SIRIUS are not generated. Very strange. I will try to see if I can set a java max memory

**Comment by eeko-kon** [comment]
OK problem solved: I was without knowing using only one thread per job and snakemake parallelizes as many jobs as possible. So with a VM of 16 CPUs, it was running sirius 16 times in parallel and that's why the momery was crashing. Live and learn. Thanks for the quick response!
