### ISSUE TITLE
SiriusAdapter does not work (release 2.8)

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#5870]
For the 2.8 conda package(s) SiriusAdapter fails because `sirius` does not know the `--db` parameter. According to sirius' CLI help it might be `[--database -d value]`?

```
INFO  19:08:59 - Sirius Workspace Successfull initialized at: /home/berntm/.sirius
INFO  19:08:59 - You run SIRIUS 4.0.1 (build 9)
INFO  19:08:59 - Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v7.5.2, CPLEX-v12.8
INFO  19:08:59 - Treebuilder priorities are: [GUROBI, CPLEX, GLPK]
INFO  19:08:59 - CPU check done. 2 cores that handle 4 threads were found.
INFO  19:08:59 - Bug reporter initialized!
SEVERE19:09:00 - Unkown Error!
com.lexicalscope.jewel.cli.ArgumentValidationException: Unexpected Option: input
Unexpected Option: project
Unexpected Option: db
	at com.lexicalscope.jewel.cli.ValidationErrorBuilderImpl.validate(ValidationErrorBuilderImpl.java:64)
	at com.lexicalscope.jewel.cli.validation.ArgumentValidatorImpl.finishedProcessing(ArgumentValidatorImpl.java:66)
	at com.lexicalscope.jewel.cli.ArgumentCollectionBuilder.processArguments(ArgumentCollectionBuilder.java:129)
	at com.lexicalscope.jewel.cli.AbstractCliImpl.parseArguments(AbstractCliImpl.java:42)
	at de.unijena.bioinf.ms.cli.CLI.parseArgs(CLI.java:358)
	at de.unijena.bioinf.ms.cli.CLI.parseArgsAndInit(CLI.java:341)
	at de.unijena.bioinf.ms.cli.FingeridCLI.parseArgsAndInit(FingeridCLI.java:62)
	at de.unijena.bioinf.ms.cli.SiriusCLIApplication.main(SiriusCLIApplication.java:46)
	at de.unijena.bioinf.ms.cli.SiriusGUIApplication.main(SiriusGUIApplication.java:102)
```

**Comment by jpfeuffer** [comment]
Thanks. I assume I specified the wrong sirius version in the conda package then.

**Comment by bernt-matthias** [comment]
Seems that its `4.0.1` .. in the `THIRDPARTY` module seems to be 4.9

**Comment by jpfeuffer** [comment]
ok yes, then we need to bump on bioconda to 4.9

**Comment by jpfeuffer** [comment]
Should be fixed on bioconda.
