### ISSUE TITLE
Missing Elements

### ISSUE THREAD

**Issue by dlon450** [OpenMS/OpenMS#5879]
Hi, just wondering if Iridium and Osmium are missing in the element database? Or how I should go about adding them in? Thanks
```
>>> EmpiricalFormula('Ir')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyopenms\pyopenms_2.pyx", line 8329, in pyopenms.pyopenms_2.EmpiricalFormula.__init__
  File "pyopenms\pyopenms_2.pyx", line 8297, in pyopenms.pyopenms_2.EmpiricalFormula._init_2 
RuntimeError: 'Ir' found. in: Unknown element 'Ir'

>>> EmpiricalFormula('Os')  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyopenms\pyopenms_2.pyx", line 8329, in pyopenms.pyopenms_2.EmpiricalFormula.__init__
  File "pyopenms\pyopenms_2.pyx", line 8297, in pyopenms.pyopenms_2.EmpiricalFormula._init_2
RuntimeError: 'Os' found. in: Unknown element 'Os'
```

**Comment by jpfeuffer** [comment]
see also #5451
