### ISSUE TITLE
SiriusAdapter issue (sirius invocation failed)

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#6032]
I just noticed this in my workflow:
```
Executing: 
FATAL: External invocation of Sirius failed. Standard output and error were:


0
QIODevice::read (QProcess): device not open
QIODevice::read (QProcess): device not open
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/Users/eeko/Desktop/pyOpenMS_untargeted_metabolomics/2_SIRIUS_CSI.ipynb Cell 5' in <module>
     [64](vscode-notebook-cell:/Users/eeko/Desktop/pyOpenMS_untargeted_metabolomics/2_SIRIUS_CSI.ipynb#ch0000004?line=63)[ out_csifingerid = os.path.join(path, 'structures_' + os.path.basename(filename)[19:-5] +".mzTab")
     ]()[65](vscode-notebook-cell:/Users/eeko/Desktop/pyOpenMS_untargeted_metabolomics/2_SIRIUS_CSI.ipynb#ch0000004?line=64)[ executable= "resources/Sirius/sirius.app/Contents/MacOS/sirius"
---> ]()[66](vscode-notebook-cell:/Users/eeko/Desktop/pyOpenMS_untargeted_metabolomics/2_SIRIUS_CSI.ipynb#ch0000004?line=65)[ subdirs = sirius_algo.callSiriusQProcess(String(sirius_tmp.getTmpMsFile()),
     ]()[67](vscode-notebook-cell:/Users/eeko/Desktop/pyOpenMS_untargeted_metabolomics/2_SIRIUS_CSI.ipynb#ch0000004?line=66)[                                         String(sirius_tmp.getTmpOutDir()),
     ]()[68](vscode-notebook-cell:/Users/eeko/Desktop/pyOpenMS_untargeted_metabolomics/2_SIRIUS_CSI.ipynb#ch0000004?line=67)[                                         String(executable),
     ]()[69](vscode-notebook-cell:/Users/eeko/Desktop/pyOpenMS_untargeted_metabolomics/2_SIRIUS_CSI.ipynb#ch0000004?line=68)[                                         String(out_csifingerid),
     ]()[70](vscode-notebook-cell:/Users/eeko/Desktop/pyOpenMS_untargeted_metabolomics/2_SIRIUS_CSI.ipynb#ch0000004?line=69)[                                         False)
     ]()[71](vscode-notebook-cell:/Users/eeko/Desktop/pyOpenMS_untargeted_metabolomics/2_SIRIUS_CSI.ipynb#ch0000004?line=70)[ candidates = sirius_algo.getNumberOfSiriusCandidates()
     ]()[72](vscode-notebook-cell:/Users/eeko/Desktop/pyOpenMS_untargeted_metabolomics/2_SIRIUS_CSI.ipynb#ch0000004?line=71)[ sirius_result = MzTab()

File ~/openms-develop/openms_build/pyOpenMS/pyopenms/pyopenms_3.pyx:10157, in pyopenms.pyopenms_3.SiriusAdapterAlgorithm.callSiriusQProcess()

RuntimeError: the value '' was used but is not valid; FATAL: SIRIUS could not be executed!]()
```
Any idea what this could be?

**Comment by jpfeuffer** [comment]
Hi!
Did this work before or are you trying this for the first time?

**Comment by eeko-kon** [comment]
It worked before  🤔

**Comment by eeko-kon** [comment]
Code:

```
path= "results/interim/sirius"
isExist= os.path.exists(path)
if not isExist:
    os.mkdir(path)

input_mzml_files = glob.glob('results/interim/mzML/PCfeature_*.mzML')
input_feature_files = glob.glob('results/interim/preprocess/MFD_*.featureXML')

for filename in input_mzml_files:
    exp = MSExperiment()
    MzMLFile().load(filename, exp)
    exp.sortSpectra(True)

feature_maps=[]
for feature_file in input_feature_files:
    fmap = FeatureMap()
    FeatureXMLFile().load(feature_file, fmap)
    feature_maps.append(fmap)

for fm in feature_maps:
    fm_no_sub = FeatureMap(fm)
    fm_no_sub.clear(False)
    for f in fm:
        f.setConvexHulls([])
        f.setSubordinates([])
        fm_no_sub.push_back(f)

    featureinfo = os.path.join(path, 'MFD_noconvexhulls_' + os.path.basename(filename)[:-5] + ".featureXML")
    FeatureXMLFile().store(featureinfo, fm_no_sub)

    sirius_algo = SiriusAdapterAlgorithm()
    sirius_algo_par = sirius_algo.getDefaults()
    sirius_algo_par.setValue("preprocessing:filter_by_num_masstraces", 2) #Number of mass traces each feature has to have to be included
    sirius_algo_par.setValue("preprocessing:feature_only", "true") #Uses the feature information from in_featureinfo to reduce the search space to MS2
    sirius_algo_par.setValue("sirius:profile", "orbitrap")
    sirius_algo_par.setValue("sirius:db", "none")
    sirius_algo_par.setValue("sirius:ions_considered", "[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+")
    sirius_algo_par.setValue("sirius:elements_enforced", "CHN[15]OS[4]") 
    sirius_algo_par.setValue("project:processors", 2)
    sirius_algo_par.setValue("fingerid:db", "BIO")
    sirius_algo.setParameters(sirius_algo_par)
        

    fm_info = FeatureMapping_FeatureMappingInfo()
    feature_mapping = FeatureMapping_FeatureToMs2Indices() 
    sirius_algo.preprocessingSirius(featureinfo,
                                    exp,
                                    fm_info,
                                    feature_mapping)
    sirius_algo.logFeatureSpectraNumber(featureinfo, 
                                        feature_mapping,
                                        exp)
                                     
    msfile = SiriusMSFile()
    debug_level = 3
    sirius_tmp = SiriusTemporaryFileSystemObjects(debug_level)
    siriusstring= String(sirius_tmp.getTmpMsFile())
    feature_only = sirius_algo.isFeatureOnly()
    isotope_pattern_iterations = sirius_algo.getIsotopePatternIterations()
    no_mt_info = sirius_algo.isNoMasstraceInfoIsotopePattern()
    compound_info = []
    msfile.store(exp,
                String(sirius_tmp.getTmpMsFile()),
                feature_mapping, 
                feature_only,
                isotope_pattern_iterations, 
                no_mt_info, 
                compound_info)
    
    out_csifingerid = os.path.join(path, 'structures_' + os.path.basename(filename)[19:-5] +".mzTab")
    executable= "resources/Sirius/sirius.app/Contents/MacOS/sirius"
    subdirs = sirius_algo.callSiriusQProcess(String(sirius_tmp.getTmpMsFile()),
                                            String(sirius_tmp.getTmpOutDir()),
                                            String(executable),
                                            String(out_csifingerid),
                                            False)
    candidates = sirius_algo.getNumberOfSiriusCandidates()
    sirius_result = MzTab()
    siriusfile = MzTabFile()
    SiriusMzTabWriter.read(subdirs,
                        filename,
                        candidates,
                        sirius_result)
    
    sirius_file= os.path.join(path,'formulas_' + os.path.basename(filename)[7:-5] +".mzTab")
    siriusfile.store(sirius_file, sirius_result)
```

Error:
```
Number of features to be processed: 26
No MS1 spectrum for this precursor. Occurred 0 times.
0 spectra were skipped due to precursor charge below -1 and above +1.
Mono charge assumed and set to charge 1 with respect to current polarity 7 times.
2 features were skipped due to feature charge below -1 and above +1.
--processors=2 --input /private/var/folders/c_/ysz9v_bd1yb7h3ymmkn6m199jbv7x7/T/20220408_131433_NNFCB-L0860.local_84748_8.ms --project /private/var/folders/c_/ysz9v_bd1yb7h3ymmkn6m199jbv7x7/T/20220408_131433_NNFCB-L0860.local_84748_7/sirius_out sirius --db=none --elements-enforced=CHN[15]OS[4] --tree-timeout=0 --candidates=5 --profile=orbitrap --ppm-max=10.0 --compound-timeout=100 --ppm-max-ms2=10.0 --ions-considered=[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+ fingerid --db=BIO --candidates=10 
Executable is: 
COMMAND:  --processors=2 --input /private/var/folders/c_/ysz9v_bd1yb7h3ymmkn6m199jbv7x7/T/20220408_131433_NNFCB-L0860.local_84748_8.ms --project /private/var/folders/c_/ysz9v_bd1yb7h3ymmkn6m199jbv7x7/T/20220408_131433_NNFCB-L0860.local_84748_7/sirius_out sirius --db=none --elements-enforced=CHN[15]OS[4] --tree-timeout=0 --candidates=5 --profile=orbitrap --ppm-max=10.0 --compound-timeout=100 --ppm-max-ms2=10.0 --ions-considered=[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+ fingerid --db=BIO --candidates=10
Executing: 
FATAL: External invocation of Sirius failed. Standard output and error were:


0
QIODevice::read (QProcess): device not open
QIODevice::read (QProcess): device not open
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [12], in <module>
     70 out_csifingerid = os.path.join(path, 'structures_' + os.path.basename(filename)[19:-5] +".mzTab")
     71 executable= "resources/Sirius/sirius.app/Contents/MacOS/sirius"
---> 72 subdirs = sirius_algo.callSiriusQProcess(String(sirius_tmp.getTmpMsFile()),
     73                                         String(sirius_tmp.getTmpOutDir()),
     74                                         String(executable),
     75                                         String(out_csifingerid),
     76                                         False)
     77 candidates = sirius_algo.getNumberOfSiriusCandidates()
     78 sirius_result = MzTab()

File pyopenms/pyopenms_3.pyx:9467, in pyopenms.pyopenms_3.SiriusAdapterAlgorithm.callSiriusQProcess()

RuntimeError: the value '' was used but is not valid; FATAL: SIRIUS could not be executed!
```

**Comment by jpfeuffer** [comment]
Oh your executable name is empty:
`COMMAND:  --processors=2 --input /private/var/folders/c_/ysz9v_bd1yb7h3ymmkn6m199jbv7x7/T/20220408_131433....`

**Comment by eeko-kon** [comment]
Yep....

**Comment by jpfeuffer** [comment]
Try without String. Either passing the raw python string `executable` or `executable.decode()` (or encode.. I always forget)

**Comment by NilouJ** [comment]
I am using the same code however I am getting another error once siriusmztabwriter.read is being called:

Number of features to be processed: 174
No MS1 spectrum for this precursor. Occurred 0 times.
1 spectra were skipped due to precursor charge below -1 and above +1.
Mono charge assumed and set to charge 1 with respect to current polarity 57 times.
2 features were skipped due to feature charge below -1 and above +1.
Executing command: /Applications/sirius.app/Contents/MacOS/sirius --noCite --processors=2 --input /private/var/folders/ny/8scj7qld1bd1cp804bslxjzh0000gq/T/20240215_113137_SCI-CJXY2FXWR3_51247_2.ms --project /private/var/folders/ny/8scj7qld1bd1cp804bslxjzh0000gq/T/20240215_113137_SCI-CJXY2FXWR3_51247_1/sirius_out --no-compression sirius --elements-enforced=CHN[15]OS[4]Cl[2]P[2] --profile=orbitrap --ions-considered=[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+ fingerprint structure write-summaries
Traceback (most recent call last):
  File "/Users/MQ10005295/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app.plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/MQ10005295/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/IntelliJ IDEA.app.plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/MQ10005295/Library/CloudStorage/OneDrive-MacquarieUniversity/Nilou/Galaxy/4_SIRIUS.py", line 111, in <module>
    oms.SiriusMzTabWriter.read(subdirs,
  File "pyopenms/_pyopenms_2.pyx", line 228, in pyopenms._pyopenms_2.__static_SiriusMzTabWriter_read
IndexError: map::at:  key not found

Process finished with exit code 1



I checked the output of the sirius and I can see report.mztab is being generated and its readable with my editor
