### ISSUE TITLE
Update min. required autowrap in pyOpenMS (new operators)

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#6124]
Sorry if this is already an open issue but it s been a few weeks that I m not able to build pyopenms. 
```
Consolidate compiler generated dependencies of target pyopenms_7
[ 92%] Built target Tutorial_AASequence
[ 92%] Built target Tutorial_MapAlignment
[ 92%] Building CXX object src/pyOpenMS/CMakeFiles/pyopenms_7.dir/__/__/pyOpenMS/pyopenms/pyopenms_7.cpp.o
/Users/eeko/openms-develop/openms_build/pyOpenMS/pyopenms/pyopenms_7.cpp:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
#error Do not use this file, it is the result of a failed Cython compilation.
 ^
1 error generated.
make[2]: *** [src/pyOpenMS/CMakeFiles/pyopenms_7.dir/__/__/pyOpenMS/pyopenms/pyopenms_7.cpp.o] Error 1
make[1]: *** [src/pyOpenMS/CMakeFiles/pyopenms_7.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Consolidate compiler generated dependencies of target pyopenms_8
Consolidate compiler generated dependencies of target pyopenms_6
Consolidate compiler generated dependencies of target pyopenms_2
[ 92%] Linking CXX shared module ../../pyOpenMS/pyopenms/pyopenms_8.cpython-39-darwin.so
[ 92%] Linking CXX shared module ../../pyOpenMS/pyopenms/pyopenms_6.cpython-39-darwin.so
[ 92%] Linking CXX shared module ../../pyOpenMS/pyopenms/pyopenms_2.cpython-39-darwin.so
Fixing typing information for pyopenms_8
Fixing typing information for pyopenms_6
Fixing typing information for pyopenms_2
Traceback (most recent call last):
  File "/Users/eeko/openms-develop/OpenMS/src/pyOpenMS/fix_pyi_imports.py", line 6, in <module>
Traceback (most recent call last):
  File "/Users/eeko/openms-develop/OpenMS/src/pyOpenMS/fix_pyi_imports.py", line 6, in <module>
    with open(args[0], 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/eeko/openms-develop/openms_build/pyOpenMS/pyopenms/pyopenms_6.pyi'
    with open(args[0], 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/eeko/openms-develop/openms_build/pyOpenMS/pyopenms/pyopenms_8.pyi'
make[2]: make[2]: *** [pyOpenMS/pyopenms/pyopenms_8.cpython-39-darwin.so] Error 1*** [pyOpenMS/pyopenms/pyopenms_6.cpython-39-darwin.so] Error 1

make[2]: make[2]: *** Deleting file `pyOpenMS/pyopenms/pyopenms_6.cpython-39-darwin.so'
*** Deleting file `pyOpenMS/pyopenms/pyopenms_8.cpython-39-darwin.so'
make[1]: *** [src/pyOpenMS/CMakeFiles/pyopenms_6.dir/all] Error 2
make[1]: *** [src/pyOpenMS/CMakeFiles/pyopenms_8.dir/all] Error 2
Traceback (most recent call last):
  File "/Users/eeko/openms-develop/OpenMS/src/pyOpenMS/fix_pyi_imports.py", line 6, in <module>
    with open(args[0], 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/eeko/openms-develop/openms_build/pyOpenMS/pyopenms/pyopenms_2.pyi'
make[2]: *** [pyOpenMS/pyopenms/pyopenms_2.cpython-39-darwin.so] Error 1
make[2]: *** Deleting file `pyOpenMS/pyopenms/pyopenms_2.cpython-39-darwin.so'
make[1]: *** [src/pyOpenMS/CMakeFiles/pyopenms_2.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by jpfeuffer** [comment]
Hi! I think then the autowrap version is too old. I think we need to increase the minimum version.

**Comment by jpfeuffer** [comment]
Ah but there also seems to be an error in compilation. Can you paste the full log?

**Comment by eeko-kon** [comment]
[log.txt](https://github.com/OpenMS/OpenMS/files/8707879/log.txt)
Is there anything more detailed than this as an output log file?

**Comment by jpfeuffer** [comment]
How did you generate that log file? Did you also reroute std error? Can you run just `make pyopenms` for now? Then you will have only the output that affects pyopenms.

**Comment by eeko-kon** [comment]
`make pyopenms -j4 > log.txt` :
It seems that the numpy API is deprecated?
[log.txt](https://github.com/OpenMS/OpenMS/files/8707996/log.txt)

**Comment by jpfeuffer** [comment]
can you do `make pyopenms -j4 > log.txt 2>&1`? I will probably need the errors as well.

**Comment by eeko-kon** [comment]
`make pyopenms -j4 > log.txt 2>&1` there you go:
[log.txt](https://github.com/OpenMS/OpenMS/files/8708025/log.txt)

**Comment by jpfeuffer** [comment]
hmm can you delete the pxds and cpps? I think it caches the results and thinks you do not need a rebuild.

**Comment by eeko-kon** [comment]
[log.txt](https://github.com/OpenMS/OpenMS/files/8708150/log.txt)
It took longer to finish the run now (I assume because of the re-generation of those files) but there is still an error.

**Comment by jpfeuffer** [comment]
Yes but now we see the error:
```
Error compiling Cython file:
------------------------------------------------------------
...
        cdef _EmpiricalFormula added = deref(this) + deref(that)
        cdef EmpiricalFormula result = EmpiricalFormula.__new__(EmpiricalFormula)
        result.inst = shared_ptr[_EmpiricalFormula](new _EmpiricalFormula(added))
        return result
    
    def operator-(self, EmpiricalFormula in_0 ):
               ^
------------------------------------------------------------

pyopenms/pyopenms_7.pyx:2917:16: Expected '(', found '-'. Did you use cdef syntax in a Python declaration? Use decorators and Python type annotations instead.
```

I think it is indeed the autowrap versoin now. Which one do you have?

**Comment by jpfeuffer** [comment]
Or Cython, can you also print you Cython version?

**Comment by eeko-kon** [comment]
Ah ok I see.
> I think it is indeed the autowrap versoin now. Which one do you have?

Metadata-Version: 2.1
Name: autowrap
Version: 0.22.6

> Or Cython, can you also print you Cython version?

Cython 0.29.29

**Comment by eeko-kon** [comment]
cpython 39

**Comment by jpfeuffer** [comment]
Yes, can you update autowrap to 0.22.8?

**Comment by eeko-kon** [comment]
pff still nothing. But isn't it a numpy issue? I ll try to update all my mamba packages. Let's see
[log.txt](https://github.com/OpenMS/OpenMS/files/8708531/log.txt)

**Comment by jpfeuffer** [comment]
did you delete the pyx and cpps again? the problem is in the autowrap step, not in the compilation. Unfortunately we don't know if autowrap produced something useful until we try to compile.
We might need to remove the caching if people have problems with it.

**Comment by jpfeuffer** [comment]
Looks good! Does it run now?

**Comment by eeko-kon** [comment]
Yeah apparently! Perfect, thank you so much. It was the autowrap after all.
