### ISSUE TITLE
Pyopenms not installable on new Macs with M1 chip

### ISSUE THREAD

**Issue by zmunro** [OpenMS/OpenMS#6163]
I have been trying for days to get pyopenms installed on my mac and I believe the issue is the M1 chip that my laptop has. When I try to run `pip install pyopenms` I get the error:

```
ERROR: Could not find a version that satisfies the requirement pyopenms (from versions: 2.3.0.linux-x86_64, 2.3.0.1.linux-x86_64, 2.3.0.2.linux-x86_64, 2.3.0.3.linux-x86_64)
ERROR: No matching distribution found for pyopenms
```

I noticed that the error says `linux` so I tried directly downloading the artifact zip from github for the MacOS wheels. When I attempted to pip install them I got similar errors:

```
ERROR: pyopenms-3.0.0-cp38-cp38-macosx_10_9_x86_64.whl is not a supported wheel on this platform.
```

Details:
macOS Monterey, version 12.1
Chip: `Apple M1 Pro`
Python version 3.9.12
Pip version 22.04

I have also attempted to install this with Python versions 3.7.13 inside of a `python:3.7-slim-buster` docker container on my local machine.

**Comment by jpfeuffer** [comment]
Hi!

Yes sorry, we currently don't have resources for an M1 build machine. And until GitHub offers hosted runners for it, we are dependent on people that build it themselves contributing it.

**Comment by jpfeuffer** [comment]
Maybe @KyowonJeong has some more insights on the state of M1 support.

**Comment by roman-bushuiev** [comment]
Hello! Are there any updates on it? I have the same problem.

**Comment by KyowonJeong** [comment]
I am checkin now with my M1. I remember I had a similar problem before. Let me dig into it and get back soon.

**Comment by roman-bushuiev** [comment]
Thanks for the reply. Unfortunately it doesn't work:
```
> pip install pyopenms
ERROR: Could not find a version that satisfies the requirement pyopenms (from versions: 2.3.0.linux-x86_64, 2.3.0.1.linux-x86_64, 2.3.0.2.linux-x86_64, 2.3.0.3.linux-x86_64)
ERROR: No matching distribution found for pyopenms
```

And the installation via conda gives me the following:
```
> conda install -c bioconda pyopenms 
PackagesNotFoundError: The following packages are not available from current channels:

  - pyopenms

Current channels:

  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
```

My versions are `Python 3.8.13`, `pip 22.1.2`, `conda 4.12.0`.

**Comment by harper357** [comment]
I have an M1 and need to install Pyopenms. Happy to help if I can.

**Comment by roman-bushuiev** [comment]
@harper357, does the installation work on your Mac?

**Comment by harper357** [comment]
It does not, so I am attempting to compile it right now.

**Comment by harper357** [comment]
I was able to compile it, but the pyopenms tests failed. It looks like it it tries to import the library, but of course it isn't yet installed. 

Trying to install it, pip crashes,
```
$ python3 -m pip install -e ./pyOpenMS
Obtaining file:///Users/[username]/Work/Git_repos/openms-development/openms_build/pyOpenMS
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages (from pyopenms==3.0.0) (1.23.3)
Collecting pandas
  Downloading pandas-1.5.0-cp310-cp310-macosx_11_0_arm64.whl (10.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 20.4 MB/s eta 0:00:00
Collecting python-dateutil>=2.8.1
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 8.2 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Using cached pytz-2022.2.1-py2.py3-none-any.whl (500 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: pytz, six, python-dateutil, pandas, pyopenms
  Running setup.py develop for pyopenms
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [40 lines of output]
        running develop
        /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        running egg_info
        creating pyopenms.egg-info
        writing pyopenms.egg-info/PKG-INFO
        writing dependency_links to pyopenms.egg-info/dependency_links.txt
        writing requirements to pyopenms.egg-info/requires.txt
        writing top-level names to pyopenms.egg-info/top_level.txt
        writing manifest file 'pyopenms.egg-info/SOURCES.txt'
        reading manifest file 'pyopenms.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        warning: no files found matching 'pyopenms/*.dll'
        warning: no files found matching 'pyopenms/*.dylib'
        warning: no files found matching 'pyopenms/*.pyd'
        warning: no directories found matching 'pyopenms/*.framework'
        warning: no files found matching 'pyopenms/Qt*'
        warning: no previously-included files matching 'pyopenms.cpp' found anywhere in distribution
        writing manifest file 'pyopenms.egg-info/SOURCES.txt'
        running build_ext
        building 'pyopenms_1' extension
        creating build
        creating build/temp.macosx-11.0-arm64-cpython-310
        creating build/temp.macosx-11.0-arm64-cpython-310/pyopenms
        /Library/Developer/CommandLineTools/usr/bin/c++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/include -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/include -arch x86_64 -DBOOST_ALL_NO_LIB -Iextra_includes -I/opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/numpy/core/include -I/Users/[username]/Work/Git_repos/openms-development/OpenMS/src/openswathalgo/include -I/Users/[username]/Work/Git_repos/openms-development/openms_build/src/openswathalgo/include -I/opt/homebrew/include -I/Users/[username]/Work/Git_repos/openms-development/OpenMS/src/openms/include -I/Users/[username]/Work/Git_repos/openms-development/openms_build/src/openms/include -I/opt/homebrew/Cellar/qt@5/5.15.5_3/include -I/Users/[username]/Work/Git_repos/openms-development/OpenMS/src/pyOpenMS/extra_includes -I/usr/local/include -I/opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/autowrap/data_files/autowrap -I/Users/[username]/Work/Git_repos/openms-development/OpenMS/src/pyOpenMS/pxds -I/opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/include/python3.10 -c pyopenms/pyopenms_1.cpp -o build/temp.macosx-11.0-arm64-cpython-310/pyopenms/pyopenms_1.o -Qunused-arguments "-Xclang -fopenmp" -std=c++17 -stdlib=libc++ -Wno-deprecated -Wno-nullability-completeness -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -Wno-redeclared-class-member -Wno-unused-local-typedefs -Wdeprecated-declarations -Wno-sign-compare -Wno-unknown-pragmas -Wno-header-guard -Wno-unused-function -Wno-deprecated-declarations -Wno-missing-declarations -Wno-int-in-bool-context
        In file included from pyopenms/pyopenms_1.cpp:783:
        In file included from /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:5:
        In file included from /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
        In file included from /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1948:
        /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
        #warning "Using deprecated NumPy API, disable it with " \
         ^
        In file included from pyopenms/pyopenms_1.cpp:892:
        /Users/[username]/Work/Git_repos/openms-development/OpenMS/src/openms/include/OpenMS/FORMAT/Base64.h:53:10: fatal error: 'QByteArray' file not found
        #include <QByteArray>
                 ^~~~~~~~~~~~
        1 warning and 1 error generated.
        error: command '/Library/Developer/CommandLineTools/usr/bin/c++' failed with exit code 1
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [40 lines of output]
    running develop
    /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running egg_info
    creating pyopenms.egg-info
    writing pyopenms.egg-info/PKG-INFO
    writing dependency_links to pyopenms.egg-info/dependency_links.txt
    writing requirements to pyopenms.egg-info/requires.txt
    writing top-level names to pyopenms.egg-info/top_level.txt
    writing manifest file 'pyopenms.egg-info/SOURCES.txt'
    reading manifest file 'pyopenms.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'pyopenms/*.dll'
    warning: no files found matching 'pyopenms/*.dylib'
    warning: no files found matching 'pyopenms/*.pyd'
    warning: no directories found matching 'pyopenms/*.framework'
    warning: no files found matching 'pyopenms/Qt*'
    warning: no previously-included files matching 'pyopenms.cpp' found anywhere in distribution
    writing manifest file 'pyopenms.egg-info/SOURCES.txt'
    running build_ext
    building 'pyopenms_1' extension
    creating build
    creating build/temp.macosx-11.0-arm64-cpython-310
    creating build/temp.macosx-11.0-arm64-cpython-310/pyopenms
    /Library/Developer/CommandLineTools/usr/bin/c++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/include -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/include -arch x86_64 -DBOOST_ALL_NO_LIB -Iextra_includes -I/opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/numpy/core/include -I/Users/[username]/Work/Git_repos/openms-development/OpenMS/src/openswathalgo/include -I/Users/[username]/Work/Git_repos/openms-development/openms_build/src/openswathalgo/include -I/opt/homebrew/include -I/Users/[username]/Work/Git_repos/openms-development/OpenMS/src/openms/include -I/Users/[username]/Work/Git_repos/openms-development/openms_build/src/openms/include -I/opt/homebrew/Cellar/qt@5/5.15.5_3/include -I/Users/[username]/Work/Git_repos/openms-development/OpenMS/src/pyOpenMS/extra_includes -I/usr/local/include -I/opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/autowrap/data_files/autowrap -I/Users/[username]/Work/Git_repos/openms-development/OpenMS/src/pyOpenMS/pxds -I/opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/include/python3.10 -c pyopenms/pyopenms_1.cpp -o build/temp.macosx-11.0-arm64-cpython-310/pyopenms/pyopenms_1.o -Qunused-arguments "-Xclang -fopenmp" -std=c++17 -stdlib=libc++ -Wno-deprecated -Wno-nullability-completeness -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -Wno-redeclared-class-member -Wno-unused-local-typedefs -Wdeprecated-declarations -Wno-sign-compare -Wno-unknown-pragmas -Wno-header-guard -Wno-unused-function -Wno-deprecated-declarations -Wno-missing-declarations -Wno-int-in-bool-context
    In file included from pyopenms/pyopenms_1.cpp:783:
    In file included from /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:5:
    In file included from /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
    In file included from /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1948:
    /opt/homebrew/Caskroom/miniforge/base/envs/build-pyopenms/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it with " \
     ^
    In file included from pyopenms/pyopenms_1.cpp:892:
    /Users/[username]/Work/Git_repos/openms-development/OpenMS/src/openms/include/OpenMS/FORMAT/Base64.h:53:10: fatal error: 'QByteArray' file not found
    #include <QByteArray>
             ^~~~~~~~~~~~
    1 warning and 1 error generated.
    error: command '/Library/Developer/CommandLineTools/usr/bin/c++' failed with exit code 1
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I have tried things like compiling without the GUI, but it still ends up with this error. Not really sure what else I can try.

**Comment by jpfeuffer** [comment]
If the tests run from the correct directory, I think it does not need to be installed globally to be imported successfully. AFAIK import will also find built modules in the current folder. At least that is what our CI is based on.
Pip install will not work, our build system is completely CMake based. You can install the wheels that are produced by the build, usually located under "dist".

**Comment by harper357** [comment]
Well maybe I made some mistake somewhere then. I followed the documentation for building OpenMS, but there is is no `dist` and no `*.whl` files anywhere.

**Comment by jpfeuffer** [comment]
Oh yes, building pyopenms is different from just building the C++ library.

https://pyopenms.readthedocs.io/en/latest/build_from_source.html

**Comment by harper357** [comment]
Thanks, I thought I was doing that, but maybe I was forgetting `make pyopenms`, but I was included `-DPYOPENMS=On` on the C++ library `make` call. 

Could it be that I am using `conda` instead of `virtualenv`?

Using conda, it looks like it is now crashing at a different point, 

```
./mac_fix_dependencies.rb:60:in `puts': stack level too deep (SystemStackError)
	from ./mac_fix_dependencies.rb:60:in `puts'
	from ./mac_fix_dependencies.rb:60:in `debug'
	from ./mac_fix_dependencies.rb:168:in `copyLib'
	from ./mac_fix_dependencies.rb:274:in `handleDyLib'
	from ./mac_fix_dependencies.rb:144:in `block in handleDependencies'
	from ./mac_fix_dependencies.rb:119:in `each'
	from ./mac_fix_dependencies.rb:119:in `handleDependencies'
	from ./mac_fix_dependencies.rb:293:in `handleDyLib'
	 ... 8725 levels...
	from ./mac_fix_dependencies.rb:400:in `each'
	from ./mac_fix_dependencies.rb:400:in `block in <main>'
	from ./mac_fix_dependencies.rb:398:in `chdir'
	from ./mac_fix_dependencies.rb:398:in `<main>'
make[3]: *** [src/pyOpenMS/CMakeFiles/pyopenms] Error 1
make[2]: *** [src/pyOpenMS/CMakeFiles/pyopenms.dir/all] Error 2
```

I won't have time to look into it for a day or two, and I am not great at Ruby, so if you have any more thoughts I can try them out.

**Comment by jpfeuffer** [comment]
Ah ok. Yes `make pyopenms` is necessary to create the `dist` folder with the wheels.
It should not matter if venv or conda. You are probably encountering a small bug in our dependency discovery code with the way that conda links its libraries. We probably need to check for infinite recursions.
But you can avoid that by not packaging dependencies (which is not necessary for conda anyway and the reason why it was not discovered yet). For conda we use our CMake option `-DNO_DEPENDENCIES` to skip that step.

**Comment by harper357** [comment]
Hmm, I tried adding  `-DNO_DEPENDENCIES=On`, but that ended up with the same error. 

I then tried using a fresh `virtualenv` instead of conda and still got the same error. 

Finally, I ended up just searching on github to see where  `mac_fix_dependencies.rb` is being called and it let me to this:
https://github.com/OpenMS/OpenMS/blob/3c4f8ba175e3d70cac7fdcaaa02642b5b2b443e9/src/pyOpenMS/CMakeLists.txt#L700

Which doesn't seem to be controlled by `NO_DEPENDENCIES`. 

However, (and I know this isn't ideal but I wanted to just quickly test it), I was then able to use the next command manually:
https://github.com/OpenMS/OpenMS/blob/3c4f8ba175e3d70cac7fdcaaa02642b5b2b443e9/src/pyOpenMS/CMakeLists.txt#L702

This managed to build the wheel which could be tested and imported 

```
$ ctest -R pyopenms
Test project /Users/[user]/Work/Git_repos/openms-development/openms_build
      Start  1: test_pyopenms_unittests
 1/26 Test  #1: test_pyopenms_unittests ....................................   Passed    8.98 sec
      Start  2: pyopenms_unittest_test000.py
 2/26 Test  #2: pyopenms_unittest_test000.py ...............................***Failed    1.37 sec
      Start  3: pyopenms_unittest_test_tutorial.py
 3/26 Test  #3: pyopenms_unittest_test_tutorial.py .........................   Passed    0.53 sec
      Start  4: pyopenms_unittest_test_BaselineFiltering.py
 4/26 Test  #4: pyopenms_unittest_test_BaselineFiltering.py ................   Passed    0.44 sec
      Start  5: pyopenms_unittest_test_ChromatogramExtractor.py
 5/26 Test  #5: pyopenms_unittest_test_ChromatogramExtractor.py ............   Passed    0.46 sec
      Start  6: pyopenms_unittest_test_ChromatogramExtractorAlgorithm.py
 6/26 Test  #6: pyopenms_unittest_test_ChromatogramExtractorAlgorithm.py ...   Passed    0.45 sec
      Start  7: pyopenms_unittest_test_Convexhull.py
 7/26 Test  #7: pyopenms_unittest_test_Convexhull.py .......................   Passed    0.39 sec
      Start  8: pyopenms_unittest_testCVTermList.py
 8/26 Test  #8: pyopenms_unittest_testCVTermList.py ........................   Passed    0.40 sec
      Start  9: pyopenms_unittest_test_DIAScoring.py
 9/26 Test  #9: pyopenms_unittest_test_DIAScoring.py .......................   Passed    0.44 sec
      Start 10: pyopenms_unittest_test_FileIO.py
10/26 Test #10: pyopenms_unittest_test_FileIO.py ...........................   Passed    0.52 sec
      Start 11: pyopenms_unittest_test_Isobaric_Quantitation.py
11/26 Test #11: pyopenms_unittest_test_Isobaric_Quantitation.py ............   Passed    0.39 sec
      Start 12: pyopenms_unittest_testLightTargetedExperiment.py
12/26 Test #12: pyopenms_unittest_testLightTargetedExperiment.py ...........   Passed    0.41 sec
      Start 13: pyopenms_unittest_test_MRMFeatureFinderScoring.py
13/26 Test #13: pyopenms_unittest_test_MRMFeatureFinderScoring.py ..........   Passed    0.53 sec
      Start 14: pyopenms_unittest_test_MSNumpressCoder.py
14/26 Test #14: pyopenms_unittest_test_MSNumpressCoder.py ..................   Passed    0.41 sec
      Start 15: pyopenms_unittest_test_MSSpectrumAndRichSpectrum.py
15/26 Test #15: pyopenms_unittest_test_MSSpectrumAndRichSpectrum.py ........   Passed    0.41 sec
      Start 16: pyopenms_unittest_test_OpenSwathDataStructures.py
16/26 Test #16: pyopenms_unittest_test_OpenSwathDataStructures.py ..........   Passed    0.42 sec
      Start 17: pyopenms_unittest_test_Smoothing.py
17/26 Test #17: pyopenms_unittest_test_Smoothing.py ........................   Passed    0.48 sec
      Start 18: pyopenms_unittest_testSpecialCases.py
18/26 Test #18: pyopenms_unittest_testSpecialCases.py ......................   Passed    0.40 sec
      Start 19: pyopenms_unittest_test_SpectraFilter.py
19/26 Test #19: pyopenms_unittest_test_SpectraFilter.py ....................   Passed    1.31 sec
      Start 20: pyopenms_unittest_test_SpectrumAccessOpenMS.py
20/26 Test #20: pyopenms_unittest_test_SpectrumAccessOpenMS.py .............   Passed    0.43 sec
      Start 21: pyopenms_unittest_test_TraML.py
21/26 Test #21: pyopenms_unittest_test_TraML.py ............................   Passed    0.45 sec
      Start 22: pyopenms_unittest_test_MzMLConsumer.py
22/26 Test #22: pyopenms_unittest_test_MzMLConsumer.py .....................   Passed    0.46 sec
      Start 23: pyopenms_unittest_test_MzXMLConsumer.py
23/26 Test #23: pyopenms_unittest_test_MzXMLConsumer.py ....................   Passed    0.40 sec
      Start 24: pyopenms_unittest_test_AcquisitionInfo.py
24/26 Test #24: pyopenms_unittest_test_AcquisitionInfo.py ..................   Passed    0.46 sec
      Start 25: pyopenms_integrationtest_test_MRMRTNormalizer.py
25/26 Test #25: pyopenms_integrationtest_test_MRMRTNormalizer.py ...........   Passed    0.53 sec
      Start 26: pyopenms_test_memoryleaktests
26/26 Test #26: pyopenms_test_memoryleaktests ..............................   Passed    9.26 sec

96% tests passed, 1 tests failed out of 26

Total Test time (real) =  30.79 sec
```
and 
```
$ ctest -R pyopenms --rerun-failed --output-on-failure
Test project /Users/[user]/Work/Git_repos/openms-development/openms_build
    Start 2: pyopenms_unittest_test000.py
1/1 Test #2: pyopenms_unittest_test000.py .....***Failed    1.30 sec
============================= test session starts ==============================
platform darwin -- Python 3.9.6, pytest-7.1.3, pluggy-1.0.0
rootdir: /Users/[user]/Work/Git_repos/openms-development/openms_build/pyOpenMS
collected 188 items

tests/unittests/test000.py ............................................. [ 23%]
........................................................................ [ 62%]
....................................................................F..  [100%]

=================================== FAILURES ===================================
____________________________ testExperimentalDesign ____________________________

    @report
    def testExperimentalDesign():
        """
        @tests: ExperimentalDesign
         ExperimentalDesign.__init__
         ExperimentalDesign.getNumberOfSamples() == 8
         ExperimentalDesign.getNumberOfFractions() == 3
         ExperimentalDesign.getNumberOfLabels() == 4
         ExperimentalDesign.getNumberOfMSFiles() == 6
         ExperimentalDesign.getNumberOfFractionGroups() == 2
         ExperimentalDesign.getSample(1, 1) == 1
         ExperimentalDesign.getSample(2, 4) == 8
         ExperimentalDesign.isFractionated()
         ExperimentalDesign.sameNrOfMSFilesPerFraction()

         ExperimentalDesignFile.__init__
         ExperimentalDesignFile.load
         """
        f = pyopenms.ExperimentalDesignFile()
        fourplex_fractionated_design = pyopenms.ExperimentalDesign()
        ed_dirname = os.path.dirname(os.path.abspath(__file__))
        ed_filename = os.path.join(ed_dirname, "ExperimentalDesign_input_2.tsv").encode()
        fourplex_fractionated_design = pyopenms.ExperimentalDesignFile.load(ed_filename, False)
        assert fourplex_fractionated_design.getNumberOfSamples() == 8
        assert fourplex_fractionated_design.getNumberOfFractions() == 3
        assert fourplex_fractionated_design.getNumberOfLabels() == 4
        assert fourplex_fractionated_design.getNumberOfMSFiles() == 6
        assert fourplex_fractionated_design.getNumberOfFractionGroups() == 2
>       assert fourplex_fractionated_design.getSample(1, 1) == 1
E       assert 0 == 1
E        +  where 0 = <built-in method getSample of pyopenms.pyopenms_4.ExperimentalDesign object at 0x127bfe250>(1, 1)
E        +    where <built-in method getSample of pyopenms.pyopenms_4.ExperimentalDesign object at 0x127bfe250> = <pyopenms.pyopenms_4.ExperimentalDesign object at 0x127bfe250>.getSample

tests/unittests/test000.py:5507: AssertionError
----------------------------- Captured stdout call -----------------------------
run  testExperimentalDesign
=========================== short test summary info ============================
FAILED tests/unittests/test000.py::testExperimentalDesign - assert 0 == 1
======================== 1 failed, 187 passed in 1.11s =========================
Attempting to call 'gnuplot' ...0 spectra and 0 chromatograms stored.
1 spectra and 0 chromatograms stored.
<1 spectra and 0 chromatograms stored.> occurred 4 times


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.37 sec

The following tests FAILED:
	  2 - pyopenms_unittest_test000.py (Failed)
Errors while running CTest
```

**Comment by jpfeuffer** [comment]
Hmm You are right, the fixing of dependencies on mac is not controlled by this. I have to think about it more to see if this needs a fix. The rb script should receive one anyway.

The test error you are seeing was fixed by me yesterday, so I would say you were successful.

Mind that you maybe can't distribute your wheels since dependencies were not copied or their link paths fixed.

**Comment by poshul** [comment]
@KyowonJeong this now works on your machine right?

**Comment by stuarthaze** [comment]
I'm experiencing the same problem. I'm using the M2 Pro chip. Did anyone find a solution?

**Comment by jpfeuffer** [comment]
Hi! It can be built (https://github.com/OpenMS/OpenMS/issues/6797) but we are not yet offering prebuilt wheels.

And I don't know about the state of bioconda regarding macOS ARM support.
