### ISSUE TITLE
[pyopenms] pickling MSExperiment/MSSpectrum

### ISSUE THREAD

**Issue by singjc** [OpenMS/OpenMS#6333]
Is it possible to pickle an **MSExperiment** object or a **MSSpectrum **object, specifically so that they can be parallelized?

I'm interested in performing some parallel processing on either the **MSExperiment** or the **MSSpectrum** objects within an **MSExperiment**. However, most parallel libraries in python (i.e. _joblib_) require pickling objects to send across workers.

However, when I try parallelizing I get an error of not being able to pickle an object: `TypeError: self.inst cannot be converted to a Python object for pickling`

This error seems to come from the **MSSpectrum** object

```
>>> spec
<pyopenms.pyopenms_1.MSSpectrum object at 0x7f99d5f0e5f0>
>>> try: 
...     with open("test_spec.pkl", "wb") as file: pickle.dump(spec, file) 
... except: 
...     traceback.print_exc(file=sys.stdout)
... 
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "stringsource", line 2, in pyopenms.pyopenms_1.MSSpectrum.__reduce_cython__
TypeError: self.inst cannot be converted to a Python object for pickling
```

I found that **MSSpectrum** actually already has a built-in `__reduce_ex__` method to aid in pickling, so I'm not sure what the issue is.

```
>>> help(spec.__reduce_ex__
... )
Help on built-in function __reduce_ex__:

__reduce_ex__(...) method of pyopenms.pyopenms_1.MSSpectrum instance
    helper for pickle
```

Is it possible to access the **MSExperiment/MSSpectrum** object in parallel?

I basically just want to perform some filtering on each spectrum in the **MSExperiment**, and would like to parallelize this process.

Thanks,

Justin

**Comment by jpfeuffer** [comment]
Hi

It think the problem is that all our extension classes contain pointers to the underlying C++ objects.
I read that Cythons autogenerated pickle helpers do not work in that case.

To be honest, I would just quickly write an apply function in C++ and wrap that.
C++ functions will have shared memory access so you don't have to do slow pickling.

**Comment by jpfeuffer** [comment]
I am not sure if you can overwrite the reduce functions for our extension classes in pure python, otherwise that would be an option.

Or you try to use parallelism from cython?
https://cython.readthedocs.io/en/latest/src/userguide/parallelism.html

**Comment by singjc** [comment]
Thank you for the suggestions! I did try overwriting the reduce function, but it's protected.

I'll try the parallelism from cython, thanks for the info!

**Comment by jpfeuffer** [comment]
Maybe you can overwrite the function by creating an inheriting class and modify that. Not ideal but you could try.

**Comment by jpfeuffer** [comment]
Hey @singjc do you have any update on this? I am very interested in what you came up with in regard to parallelization. In case you found something nice it might be helpful to write a little section in the documentation.
