### ISSUE TITLE
TOPPView: Error loading input file for TOPP tool

### ISSUE THREAD

**Issue by axelwalter** [OpenMS/OpenMS#6637]
Running a TOPP tool (whole layer or visible layer) raises the error that input file can not be found (tested with multiple tools):

```
12:59:07 NOTICE: Starting 'FileFilter'
Warning: Parameters file version (2.8.0) does not match the version of this tool (3.0.0-pre-develop-2023-01-30).
Your current parameters are still valid, but there might be new valid values or even new parameters. Upgrading the INI might be useful.
Cannot read input file given from parameter '-in'!
Error: File not found (the file '/tmp/TOPPView_20230131_125849_a2_35875_176_in' could not be found)
```

In that example case the file is present at location `/tmp/TOPPView_20230131_125849_a2_35875_176` without the `_in` suffix.

Tested on Ubuntu 22.10.

**Comment by JeeH-K** [comment]
The same error was in MacOS (tested on Ventura 13.1). 
![Screenshot 2023-02-01 at 7 57 21 PM](https://user-images.githubusercontent.com/7207883/216137310-21db7b34-be65-45b1-a4b8-f4231356bdc5.png)

Even with the example file, it didn't work
```
19:57:26 NOTICE: Starting 'BaselineFilter'
Cannot read input file given from parameter '-in'!
Error: File not found (the file '/private/var/folders/b2/tzs638qn2r97q8hjmlv6gmh80000gp/T/TOPPView_20230201_195625_Kims-MBP.fritz.box_9417_174_in' could not be found)


==============================================================================
19:57:27 ERROR: Execution of 'BaselineFilter' not successful!
The tool ended with a non-zero exit code of '1'. If you want to debug this, check the input files in '/private/var/folders/b2/tzs638qn2r97q8hjmlv6gmh80000gp/T' or enable 'debug' mode in the TOPP ini file.

```

**Comment by KyowonJeong** [comment]
The same goes here in Windows 10.

**Comment by timosachsenberg** [comment]
can confirm:
some gdb traces
```
#0  0x00007ffff307df38 in QString::reallocData(unsigned int, bool) ()
   from /home/sachsenb/miniconda3/lib/libQt5Core.so.5
#1  0x00007ffff39afbf2 in QWidgetLineControl::updateDisplayText(bool) ()
   from /home/sachsenb/miniconda3/lib/libQt5Widgets.so.5
#2  0x00007ffff39b18a4 in QWidgetLineControl::finishChange(int, bool, bool) ()
   from /home/sachsenb/miniconda3/lib/libQt5Widgets.so.5
#3  0x00007ffff39b1a5d in QWidgetLineControl::internalSetText(QString const&, int, bool) ()
   from /home/sachsenb/miniconda3/lib/libQt5Widgets.so.5
#4  0x00007ffff3a37c69 in QInputDialog::getText(QWidget*, QString const&, QString const&, QLineEdit::EchoMode, QString const&, bool*, QFlags<Qt::WindowType>, QFlags<Qt::InputMethodHint>) ()
   from /home/sachsenb/miniconda3/lib/libQt5Widgets.so.5
#5  0x00007ffff782a1b2 in OpenMS::Annotation1DItem::editText (this=0x7fffffffc400)
```

```
93        bool Annotation1DItem::editText()
94        {
95          bool ok;
--->96          QString text = QInputDialog::getText(nullptr, "Edit text", "Enter text:", QLineEdit::Normal, this->getText(), &ok);
97          if (ok && !text.isEmpty())
98          {
99            if (text == getText())
100           {
```

**Comment by KyowonJeong** [comment]
On Windows10, the tools are working in the new version.
