### ISSUE TITLE
[pyOpenMS plotting] simple code in docs "plot_spectrum" is not working with nightly

### ISSUE THREAD

**Issue by JeeH-K** [OpenMS/OpenMS#6701]
Simple code in the docs doesn't work. "plot_spectrum"
https://pyopenms.readthedocs.io/en/latest/theoreticalspectrumgenerator.html
tested on the nightly-wheel build version.

1. 
```
import matplotlib.pyplot as plt

plot_spectrum(spec1)
plt.show()
```
Error as:
```
Traceback (most recent call last):
  File "/Users/jeek/openms-docs/theoreticalSpectrumGeneratorTester.py", line 46, in <module>
    plot_spectrum(spec1)
NameError: name 'plot_spectrum' is not defined
```

It has to be
```
from pyopenms import plotting
plotting.plot_spectrum(spec1)
```
to be reached, which is weirdly not covered by 
```from pyopenms import *```

2.
```plotting.plot_spectrum(spec1)``` gives error as
```
Traceback (most recent call last):
  File "/Users/jeek/openms-docs/theoreticalSpectrumGeneratorTester.py", line 45, in <module>
    plotting.plot_spectrum(spec1)
  File "/Users/jeek/.local/share/virtualenvs/openms-docs-lTJr_OfQ/lib/python3.9/site-packages/pyopenms/plotting.py", line 356, in plot_spectrum
    ax.grid(b=True, which='major', color='#9E9E9E', linewidth=0.2)
  File "/Users/jeek/.local/share/virtualenvs/openms-docs-lTJr_OfQ/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3196, in grid
    self.xaxis.grid(visible, which=which, **kwargs)
  File "/Users/jeek/.local/share/virtualenvs/openms-docs-lTJr_OfQ/lib/python3.9/site-packages/matplotlib/axis.py", line 1655, in grid
    self.set_tick_params(which='major', **gridkw)
  File "/Users/jeek/.local/share/virtualenvs/openms-docs-lTJr_OfQ/lib/python3.9/site-packages/matplotlib/axis.py", line 927, in set_tick_params
    kwtrans = self._translate_tick_params(kwargs)
  File "/Users/jeek/.local/share/virtualenvs/openms-docs-lTJr_OfQ/lib/python3.9/site-packages/matplotlib/axis.py", line 1071, in _translate_tick_params
    raise ValueError(
ValueError: keyword grid_b is not recognized; valid keywords are ['size', 'width', 'color', 'tickdir', 'pad', 'labelsize', 'labelcolor', 'zorder', 'gridOn', 'tick1On', 'tick2On', 'label1On', 'label2On', 'length', 'direction', 'left', 'bottom', 'right', 'top', 'labelleft', 'labelbottom', 'labelright', 'labeltop', 'labelrotation', 'grid_agg_filter', 'grid_alpha', 'grid_animated', 'grid_antialiased', 'grid_clip_box', 'grid_clip_on', 'grid_clip_path', 'grid_color', 'grid_dash_capstyle', 'grid_dash_joinstyle', 'grid_dashes', 'grid_data', 'grid_drawstyle', 'grid_figure', 'grid_fillstyle', 'grid_gapcolor', 'grid_gid', 'grid_in_layout', 'grid_label', 'grid_linestyle', 'grid_linewidth', 'grid_marker', 'grid_markeredgecolor', 'grid_markeredgewidth', 'grid_markerfacecolor', 'grid_markerfacecoloralt', 'grid_markersize', 'grid_markevery', 'grid_mouseover', 'grid_path_effects', 'grid_picker', 'grid_pickradius', 'grid_rasterized', 'grid_sketch_params', 'grid_snap', 'grid_solid_capstyle', 'grid_solid_joinstyle', 'grid_transform', 'grid_url', 'grid_visible', 'grid_xdata', 'grid_ydata', 'grid_zorder', 'grid_aa', 'grid_c', 'grid_ds', 'grid_ls', 'grid_lw', 'grid_mec', 'grid_mew', 'grid_mfc', 'grid_mfcalt', 'grid_ms']
```
 This doesn't happen if I turn off the grid option as
```plotting.plot_spectrum(spec1, grid=False)``` 

3.
Adding precursor ions gives an error. (i.e, ```p.setValue("add_precursor_peaks", "true")```)
```
Traceback (most recent call last):
  File "/Users/jeek/openms-docs/theoreticalSpectrumGeneratorTester.py", line 46, in <module>
    plotting.plot_spectrum(spec1)
  File "/Users/jeek/.local/share/virtualenvs/openms-docs-lTJr_OfQ/lib/python3.9/site-packages/pyopenms/plotting.py", line 345, in plot_spectrum
    color, zorder = _annotate_ion(
  File "/Users/jeek/.local/share/virtualenvs/openms-docs-lTJr_OfQ/lib/python3.9/site-packages/pyopenms/plotting.py", line 255, in _annotate_ion
    raise ValueError('Ion type not supported')
ValueError: Ion type not supported
``` 
Maybe precursor ions should always be excluded from the drawing plots?

The test code is as below:
```
from pyopenms import *

tsg = TheoreticalSpectrumGenerator()
spec1 = MSSpectrum()
peptide = AASequence.fromString("DFPIANGER")
# standard behavior is adding b- and y-ions of charge 1
p = Param()
p.setValue("add_b_ions", "false")
p.setValue("add_metainfo", "true")
p.setValue("add_precursor_peaks", "true")
tsg.setParameters(p)
tsg.getSpectrum(spec1, peptide, 1, 1)  # charge range 1:1

# Iterate over annotated ions and their masses
print("Spectrum 1 of", peptide, "has", spec1.size(), "peaks.")
for ion, peak in zip(spec1.getStringDataArrays()[0], spec1):
    print(ion.decode(), "is generated at m/z", peak.getMZ())

from pyopenms import plotting
plotting.plot_spectrum(spec1)
# plot_spectrum(spec1)
plt.show()
```

Can anyone help me solve these issues? I'd like to open a pull request after knowing a solution.

**Comment by jpfeuffer** [comment]
2. Is standard python behaviour. You cannot wildcard import submodules.

**Comment by jpfeuffer** [comment]
2. Is probably a bug that needs fixing.
3. Just not implemented. Would be easy to add and imho would be a nice feature.

**Comment by JeeH-K** [comment]
Hi @jpfeuffer , thanks for the suggestions.

1. I don't get what you mean by "is wrong." You mean using the wild card? It's in the example code in the link and quite widely used like that in the pyopenms tutorials. I personally didn't agree to use it like that, but since most of the example codes are written like that, I thought we should be consistent with it.

2. and 3. I'll work on it.

**Comment by matteopilz** [comment]
1. My bad, I have updated the plotting documentation, but overlooked the imports. I will fix it immediately. The correct import should be `from pyopenms.plotting import plot_spectrum`.

**Comment by jpfeuffer** [comment]
@matteopilz Please do not direct commit. Create a PR, make sure that CI actually tests your code (which it did not do correctly last time, see my new issue), then merge.
