### ISSUE TITLE
Pyopenms docs have errors due to changes in SVM wrappings

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6804]
```
WARNING: autodoc: failed to import class 'SVMPrediction' from module 'pyopenms'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/jpfeuffer/mambaforge/envs/openms-docs/lib/python3.10/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'pyopenms' has no attribute 'SVMPrediction'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jpfeuffer/mambaforge/envs/openms-docs/lib/python3.10/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/Users/jpfeuffer/mambaforge/envs/openms-docs/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Users/jpfeuffer/mambaforge/envs/openms-docs/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Users/jpfeuffer/mambaforge/envs/openms-docs/lib/python3.10/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: SVMPrediction

WARNING: autodoc: failed to import class 'SimpleSVM' from module 'pyopenms'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/jpfeuffer/mambaforge/envs/openms-docs/lib/python3.10/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'pyopenms' has no attribute 'SimpleSVM'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jpfeuffer/mambaforge/envs/openms-docs/lib/python3.10/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/Users/jpfeuffer/mambaforge/envs/openms-docs/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Users/jpfeuffer/mambaforge/envs/openms-docs/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Users/jpfeuffer/mambaforge/envs/openms-docs/lib/python3.10/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: SimpleSVM
```

**Comment by jpfeuffer** [comment]
Solution: remove completely from pyopenms.
