### ISSUE TITLE
GNPSexport fails with Bruker Maxis mzML files

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#6881]
Hi! Unfortunately, I cannot resolve the error or locate its origin. GNPSexport fails almost immediately with a group of files that do not seem corrupted. All the other steps (FFM, MapAlignment, FileFiltering, etc) seem to run fine, but GNPSexport produces the following error (debug 9):

```
Progress of 'parsing features and ms2 identifications...':
  0.30 %               /bin/bash: line 1: 20984 Abort trap: 6 

Error, intensity or m/z array is missing, skipping this spectrum
libc++abi: terminating due to uncaught exception of type std::out_of_range: vector
```

Any idea where that could come from? The consensus seems like the mzML file has a bit different metadata than the typical Thermo one. Could that be it?

Consensus example of features with MSMS info:

```
		<consensusElement id="e_6856703783701907356" quality="1.944292e-04" charge="1">
			<centroid rt="1328.633269066394405" mz="271.263258270421488" it="8.491879e05"/>
			<groupedElementList>
				<element map="0" id="868321311271805085" rt="1329.361000000000104" mz="271.262757120722199" it="9.190022e05" charge="1"/>
				<element map="1" id="147101269496669126" rt="1329.33746371234156" mz="271.263768566296221" it="1.122436e06" charge="1"/>
				<element map="2" id="13562308145568367099" rt="1328.842877413245105" mz="271.263132028911173" it="1.210901e06" charge="1"/>
				<element map="3" id="13284064824326029769" rt="1328.864867415145909" mz="271.263172971932249" it="1.113409e06" charge="1"/>
				<element map="4" id="12467837171538526261" rt="1327.396800843902156" mz="271.262945489292349" it="4.895144e05" charge="1"/>
				<element map="5" id="13637263624088940778" rt="1328.346791960423843" mz="271.263214928172204" it="6.480557e05" charge="1"/>
				<element map="6" id="14025849503840184601" rt="1328.163350456688704" mz="271.263640645492444" it="3.34229e05" charge="1"/>
				<element map="7" id="7976739177690559049" rt="1328.753000729407177" mz="271.263434412553011" it="9.559558e05" charge="1"/>
			</groupedElementList>
			<PeptideIdentification identification_run_ref="PI_1" score_type="" higher_score_better="true" significance_threshold="0" MZ="271.263768566296" RT="39.6919381445374" spectrum_reference="scan=58" >
				<UserParam type="int" name="spectrum_index" value="57"/>
				<UserParam type="int" name="map_index" value="1"/>
			</PeptideIdentification>
			<PeptideIdentification identification_run_ref="PI_3" score_type="" higher_score_better="true" significance_threshold="0" MZ="271.263310071862" RT="1352.57152750668" spectrum_reference="scan=2660" >
				<UserParam type="int" name="spectrum_index" value="2659"/>
				<UserParam type="int" name="map_index" value="3"/>
			</PeptideIdentification>
			<PeptideIdentification identification_run_ref="PI_7" score_type="" higher_score_better="true" significance_threshold="0" MZ="271.263574098505" RT="1352.45569449455" spectrum_reference="scan=2660" >
				<UserParam type="int" name="spectrum_index" value="2659"/>
				<UserParam type="int" name="map_index" value="7"/>
			</PeptideIdentification>
			<UserParam type="string" name="best ion" value="[M+H]+"/>
			<UserParam type="stringList" name="LinkedGroups" value="[3019471735609727264,9696828725719829130,1611796438568869432,2623568231338656532,7307788932734372935,16213831360059764362,17832336752849361797,2498196845940682788]"/>
```

Said peak information in an mzML file:

```
        </spectrum>
        <spectrum index="2774" id="scan=2775" defaultArrayLength="6">
          <cvParam cvRef="MS" accession="MS:1000511" name="ms level" value="2"/>
          <cvParam cvRef="MS" accession="MS:1000580" name="MSn spectrum" value=""/>
          <cvParam cvRef="MS" accession="MS:1000130" name="positive scan" value=""/>
          <cvParam cvRef="MS" accession="MS:1000505" name="base peak intensity" value="5952.0"/>
          <cvParam cvRef="MS" accession="MS:1000285" name="total ion current" value="10166.0"/>
          <cvParam cvRef="MS" accession="MS:1000127" name="centroid spectrum" value=""/>
          <cvParam cvRef="MS" accession="MS:1000796" name="spectrum title" value="Regul_Pert_02524_2_c9_B_10d_RB8_01_63431.2775.2775. File:&quot;Regul_Pert_02524_2_c9_B_10d_RB8_01_63431.d&quot;, NativeID:&quot;scan=2775&quot;"/>
          <scanList count="1">
            <cvParam cvRef="MS" accession="MS:1000795" name="no combination" value=""/>
            <scan>
              <cvParam cvRef="MS" accession="MS:1000016" name="scan start time" value="1410.633" unitCvRef="UO" unitAccession="UO:0000010" unitName="second"/>
              <scanWindowList count="1">
                <scanWindow>
                  <cvParam cvRef="MS" accession="MS:1000501" name="scan window lower limit" value="50.0" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                  <cvParam cvRef="MS" accession="MS:1000500" name="scan window upper limit" value="1250.0" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                </scanWindow>
              </scanWindowList>
            </scan>
          </scanList>
          <precursorList count="1">
            <precursor>
              <isolationWindow>
                <cvParam cvRef="MS" accession="MS:1000827" name="isolation window target m/z" value="271.263305664063" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                <cvParam cvRef="MS" accession="MS:1000828" name="isolation window lower offset" value="2.42815823873" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                <cvParam cvRef="MS" accession="MS:1000829" name="isolation window upper offset" value="2.42815823873" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
              </isolationWindow>
              <selectedIonList count="1">
                <selectedIon>
                  <cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="271.263305664063" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                </selectedIon>
              </selectedIonList>
              <activation>
                <cvParam cvRef="MS" accession="MS:1000133" name="collision-induced dissociation" value=""/>
              </activation>
            </precursor>
          </precursorList>
          <binaryDataArrayList count="2">
            <binaryDataArray encodedLength="80">
              <cvParam cvRef="MS" accession="MS:1000523" name="64-bit float" value=""/>
              <cvParam cvRef="MS" accession="MS:1000574" name="zlib compression" value=""/>
              <cvParam cvRef="MS" accession="MS:1000514" name="m/z array" value="" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
              <binary>eJwBMADP/8iD7b3WxFlAfNsKw9xFXUCR2UvxPaRiQGK6qbm+HmxACO+nzzn0cEAmDMcgSARxQIPQF5o=</binary>
            </binaryDataArray>
            <binaryDataArray encodedLength="48">
              <cvParam cvRef="MS" accession="MS:1000523" name="64-bit float" value=""/>
              <cvParam cvRef="MS" accession="MS:1000574" name="zlib compression" value=""/>
              <cvParam cvRef="MS" accession="MS:1000515" name="intensity array" value="" unitCvRef="MS" unitAccession="MS:1000131" unitName="number of detector counts"/>
              <binary>eJxjYACCiCkOIIphQhuEvlANoRfUQmiH7RD6zmQHALD0CFE=</binary>
            </binaryDataArray>
          </binaryDataArrayList>
```

**Comment by timosachsenberg** [comment]
taking notes for myself:
```
#0  __cxxabiv1::__cxa_throw (obj=0x55555623b0d0, tinfo=0x7ffff4a78208 <typeinfo for std::out_of_range>, dest=0x7ffff49380d0 <std::out_of_range::~out_of_range()>)
    at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_throw.cc:77
#1  0x00007ffff491a286 in std::__throw_out_of_range_fmt(char const*, ...) [clone .cold] () at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/src/c++98/bitmap_allocator.cc:92
#2  0x00007ffff642acf8 in std::vector<OpenMS::Peak1D, std::allocator<OpenMS::Peak1D> >::_M_range_check (this=0x7fffffffc2c0, __n=0) at /usr/include/c++/9/bits/stl_vector.h:1070
#3  0x00007ffff642a47d in std::vector<OpenMS::Peak1D, std::allocator<OpenMS::Peak1D> >::at (this=0x7fffffffc2c0, __n=0) at /usr/include/c++/9/bits/stl_vector.h:1109
#4  0x00007ffff642401b in OpenMS::binPeaks_ (peaks=..., bin_width=0.019999999552965164, binned_peaks=...) at /home/sachsenb/OMS/OpenMS/src/openms/source/FORMAT/GNPSMGFFile.cpp:87
#5  0x00007ffff64243df in OpenMS::flattenAndBinSpectra_ (exp=..., bin_width=0.019999999552965164, merged_peaks=...) at /home/sachsenb/OMS/OpenMS/src/openms/source/FORMAT/GNPSMGFFile.cpp:146
#6  0x00007ffff64259af in OpenMS::GNPSMGFFile::store (this=0x7fffffffd6d0, consensus_file_path=..., mzml_file_paths=..., out=...) at /home/sachsenb/OMS/OpenMS/src/openms/source/FORMAT/GNPSMGFFile.cpp:385
#7  0x000055555555b65e in TOPPGNPSExport::main_ (this=0x7fffffffdec0) at /home/sachsenb/OMS/OpenMS/src/topp/GNPSExport.cpp:184
#8  0x00007ffff735e6f3 in OpenMS::TOPPBase::main (this=0x7fffffffdec0, argc=18, argv=0x7fffffffe5c8) at /home/sachsenb/OMS/OpenMS/src/openms/source/APPLICATIONS/TOPPBase.cpp:452
#9  0x0000555555557932 in main (argc=18, argv=0x7fffffffe5c8) at /home/sachsenb/OMS/OpenMS/src/topp/GNPSExport.cpp:198


(gdb) frame 4
#4  0x00007ffff642401b in OpenMS::binPeaks_ (peaks=..., bin_width=0.019999999552965164, binned_peaks=...) at /home/sachsenb/OMS/OpenMS/src/openms/source/FORMAT/GNPSMGFFile.cpp:87
87          double last_mz = peaks.at(0).getMZ();
(gdb) print peaks.size()
$1 = 0


385           flattenAndBinSpectra_(
(gdb) list
380             }
381           }
382
383           // store outputted peaks in vector<Peak1D>
384           vector<Peak1D> peaks;
385           flattenAndBinSpectra_(
386             exp,
387             bin_width,
388             peaks
389           );
(gdb) print exp.size()
$5 = 1
(gdb) print exp[0].size()
$6 = 0


```

**Comment by timosachsenberg** [comment]
best spectrum (highest precursor intensity) without peaks
```
(gdb) print best_speci
$16 = 1833
(gdb) print best_spec.getRT()
$17 = 938.05799999999999
```
