### ISSUE TITLE
Cython 3

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6982]
Apparently, Cython 3 was finally released and our builds are failing.
Can't see why through all the new warnings.

**Comment by timosachsenberg** [comment]
which builds? pyopenmsdkr
```
  �� python setup.py egg_info did not run successfully.
  ��� exit code: 1
  ������> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/jenkins/ws/openms/PR/pyOMSDckr/OpenMS-build/pyOpenMS/setup.py", line 288
          "Documentation Source": "https://github.com/OpenMS/pyopenms-docs",
                                ^
      SyntaxError: invalid syntax
      [end of output]
```

or related to this warnings caused by many files?
```
warning: /home/jenkins/ws/openms/PR/pyOMSDckr/OpenMS/src/pyOpenMS/pxds/ParamCTDFile.pxd:9:41: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
```

**Comment by jpfeuffer** [comment]
Ok, then it was just this specific PR. Still, we need to get rid of the warnings or else we will not see anything anymore.

**Comment by timosachsenberg** [comment]
k I will try to come up with a regex

**Comment by jpfeuffer** [comment]
I dont think this can be fixed by a regex. You need to adapt autowrap or our pxds to put the nogil at a different place.

**Comment by timosachsenberg** [comment]
yeah I mean the pxds

**Comment by jpfeuffer** [comment]
Ah I see!
