### ISSUE TITLE
Running MSGF+ in parallel crashes when input DB is new

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#7255]
MSGF+ creates in indexed DB from a FASTA file if it does not find one.
If two instances of MSGF+ run in parallel, they will both try to write/read the same index files and crash with:
```


Standard error: java.lang.NumberFormatException: For input string: ""

	at java.lang.NumberFormatException.forInputString(Unknown Source)

	at java.lang.Integer.parseInt(Unknown Source)

	at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.readMetaInfo(CompactFastaSequence.java:516)

<	at java.lang.Integer.parseInt(Unknown Source)
> occurred 2 times
	at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.<init>(CompactFastaSequence.java:142)

	at edu.ucsd.msjava.msdbsearch.CompactFastaSequence.<init>(CompactFastaSequence.java:89)

	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:235)

	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:113)

	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:61)

Process 'C:/Program Files (x86)/Common Files/Oracle/Java/javapath/java.EXE' did not finish successfully (exit code: ÿ). Please check the log.
```

Our options are:
Have the MSGFAdapter search for the indexed files and
either:
a) abort if index is missing 
b) copy the FASTA file to a temporary directory (where MSGF+ will create an index, which is lost after the adapter finishes)
c) if index is missing, create it, but use some kind of locking mechanism which only allows one adapter to do this

Solution 
a) is the easiest, but also very inconvenient for the user, especially in workflows which use 'DecoyDatabase'; Could be mitigated if the implement a separate MSGFPlus_DB_Adapter, which simply creates the Index; This new Node could be placed right behind DecoyDatabase and thus avoids concurrency issues.
b) is foolproof, but a bit inefficient, especially for very large DB's; could be mitigated by issuing a warning to the user
c) technically challenging to implement locks cross-platform, but convenient and efficient

**Comment by cbielow** [comment]
Note: there is https://msgfplus.github.io/msgfplus/BuildSA.html, which allows to build the Index without calling MGSF+
