### ISSUE TITLE
OpenMS is not working

### ISSUE THREAD

**Issue by clin888** [OpenMS/OpenMS#7333]
Hi,

The following message was found when generated a spectrum library using DDA data. Please help
Thanks

Traceback (most recent call last):
File "C:\ProgramData\Python_3.9\Scripts\easypqp-script.py", line 33, in
sys.exit(load_entry_point('easypqp==0.1.42', 'console_scripts', 'easypqp')())
File "C:\ProgramData\Python_3.9\Scripts\easypqp-script.py", line 25, in importlib_load_entry_point
return next(matches).load()
File "C:\ProgramData\Python_3.9\lib\importlib\metadata.py", line 86, in load
module = import_module(match.group('module'))
File "C:\ProgramData\Python_3.9\lib\importlib_init_.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1030, in _gcd_import
File "", line 1007, in _find_and_load
File "", line 986, in _find_and_load_unlocked
File "", line 680, in load_unlocked
File "", line 850, in exec_module
File "", line 228, in call_with_frames_removed
File "C:\ProgramData\Python_3.9\lib\site-packages\easypqp\main.py", line 9, in
from .convert import conversion, basename_spectralfile
File "C:\ProgramData\Python_3.9\lib\site-packages\easypqp\convert.py", line 18, in
import pyopenms as po
File "C:\ProgramData\Python_3.9\lib\site-packages\pyopenms_init.py", line 107, in
raise e
File "C:\ProgramData\Python_3.9\lib\site-packages\pyopenms_init.py", line 65, in
from ._all_modules import * # pylint: disable=wildcard-import; lgtm(py/polluting-import)
File "C:\ProgramData\Python_3.9\lib\site-packages\pyopenms_all_modules.py", line 1, in
from ._pyopenms_1 import * # pylint: disable=wildcard-import; lgtm(py/polluting-import)
ImportError: DLL load failed while importing _pyopenms_1: A dynamic link library (DLL) initialization routine failed.

======================================================================
Error when loading pyOpenMS libraries!
Libraries could not be found / could not be loaded.

To debug this error, please run ldd (on linux), otool -L (on macOS) or dependency walker (on windows) on

C:\ProgramData\Python_3.9\lib\site-packages\pyopenms\pyopenms*.so

======================================================================
Traceback (most recent call last):
File "C:\Fragpipe\FragPipe-jre-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 724, in
main_easypqp()
File "C:\Fragpipe\FragPipe-jre-21.1\fragpipe\tools\speclib\gen_con_spec_lib.py", line 566, in main_easypqp
subprocess.run([os.fspath(easypqp), '--version'], check=True)
File "C:\ProgramData\Python_3.9\lib\subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\ProgramData\Python_3.9\Scripts\easypqp.exe', '--version']' returned non-zero exit status 1.
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

[log_2024-02-04_16-55-51.txt](https://github.com/OpenMS/OpenMS/files/14169401/log_2024-02-04_16-55-51.txt)

**Comment by jpfeuffer** [comment]
Hi!

I think you might be getting this error because of one of the following reasons:

- You are running 32-bit Python or a 32-bit Windows
- You have not installed the Microsoft Visual C++ Redistributable package
- Your CPU does not support certain SIMD (AVX?) instructions

Let us know if you need help checking any of those facts.

Tagging @cbielow as a windows and SIMD expert.

**Comment by clin888** [comment]
Hi,

Thank you for your help,

You are running 32-bit Python or a 32-bit Windows
--I run 64-bit Python with 64-bit window 10 enterprise
You have not installed the Microsoft Visual C++ Redistributable package
--I have Microsoft Visual C++ Redistributable package installed
Your CPU does not support certain SIMD (AVX?) instructions
--The CPU is intel Xeon ES 530 and it should support AVX

Thanks

**Comment by jpfeuffer** [comment]
Hm ok. 
Can you list the DLLs or pyds in C:\ProgramData\Python_3.9\lib\site-packages\pyopenms?
And potentially even run DependencyWalker on any of the _pyopenms.dlls or .pyds and post a screenshot? https://lucasg.github.io/Dependencies/

**Comment by clin888** [comment]
Hi,

Thank you for your efforts. Enclosed is a screenshot for Dependency and Pyopenms

[pyopenms_file_list.docx](https://github.com/OpenMS/OpenMS/files/14172539/pyopenms_file_list.docx)
.

**Comment by jpfeuffer** [comment]
Thank you very much for your quick and helpful debugging.
Unfortunately, your screenshots actually look very much correct. I think "Dependencies" should show some dependent DLLs as red, in case they are missing or incompatible.
Maybe run dependencies on _pyopenms_1.cp39-win_amd64 and quickly scroll through the dependency list to check that there is nothing marked in the color red.

**Comment by jkennedy-hutch** [comment]
Good afternoon,

  I'd like to take over where clin888 left off - he's currently out of the lab for a while.  Attached is a screenshot of the dependencies for _pyopenms_1.cp39-win_amd64.  It looks like there's one in red and a couple libraries with bad checksums.  Are these our culprits?

Thanks,
-Jake
![dependencies](https://github.com/OpenMS/OpenMS/assets/167481582/1c2bf509-456e-4458-a225-35880e9142a8)

**Comment by jpfeuffer** [comment]
Hi!

Maybe the missing ordinals are a problem, but they are from a system library, not anything that we ship.
The incorrect checksums are less likely to be a problem, I don't think they are checked by default during loading (I think a checksum of 0 just means we don't encode any into the DLL).

Can you try in whatever python (environment) this code is called by fragpipe to run:

```
import dlltracer
import sys
with dlltracer.Trace(out=sys.stdout):
    import pyopenms
    print(pyopenms.__version__)
```

To potentially debug at which library it really crashes.
(I found this somewhere, never tried myself)

**Comment by jkennedy-hutch** [comment]
Thank you very much for your help looking in on our problem!  Unfortunately, I’m getting a ModuleNotFoundError when trying to call dlltracer.  Where were you able to find this?  Thanks for all of your help!

**Comment by jpfeuffer** [comment]
Oh yes, you need to `pip install dlltracer` into that env first. I forgot.

**Comment by jkennedy-hutch** [comment]
Of course.  Sorry about that!  Here’s what I get back:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_native.pyx", line 285, in dlltracer._native.Trace.__enter__
  File "_native.pyx", line 306, in dlltracer._native.Trace.start
  File "_native.pyx", line 186, in dlltracer._native._check
PermissionError: [WinError 5] failed to start trace (0x00000005)

**Comment by jpfeuffer** [comment]
Hmmm can you try running it from an elevated/admin command line or python Run as Administrator?
Do you have those permissions? I think they are unfortunately necessary for this kind of debugging.

**Comment by jkennedy-hutch** [comment]
Unfortunately I don’t have admin rights on either of the 2 workstations that we’re trying to run this.  Could that be our problem?

**Comment by jpfeuffer** [comment]
In theory it should not affect the execution but I cannot guarantee. Maybe it's also the way that fragpipe calls easypqp that calls pyopenms.. (and the permissions involved in spawning those subprocesses or accessing files/dlls)

Can you try just importing pyopenms in the python env? This should "work" without admin permissions (or at least fail with the initial error).

Other options are trying a fresh Windows virtual machine or so, to see if it's reproducible.

Unfortunately I do not have Windows, therefore we depend on GitHub's public runners, on which pyopenms works on a fresh "installation"

**Comment by jkennedy-hutch** [comment]
Looks like I got the same error in the python env (below).  Also, we did wipe this Windows machine & start from scratch to try & fix this issue.  We figured we’d try that before bugging you!  Thank you very much for your time!

Warning: OPENMS_DATA_PATH environment variable already exists. pyOpenMS will use it (C:\Program Files\OpenMS-3.1.0\share\OpenMS) to locate data in the OpenMS share folder (e.g., the unimod database), instead of the default (C:\ProgramData\Python_3.9\lib\site-packages\pyopenms\share/OpenMS).

======================================================================
Error when loading pyOpenMS libraries!
Libraries could not be found / could not be loaded.

To debug this error, please run ldd (on linux), otool -L (on macOS) or dependency walker (on windows) on

C:\ProgramData\Python_3.9\lib\site-packages\pyopenms\pyopenms*.so

======================================================================
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Python_3.9\lib\site-packages\pyopenms\__init__.py", line 107, in <module>
    raise e
  File "C:\ProgramData\Python_3.9\lib\site-packages\pyopenms\__init__.py", line 65, in <module>
    from ._all_modules import *  # pylint: disable=wildcard-import; lgtm(py/polluting-import)
  File "C:\ProgramData\Python_3.9\lib\site-packages\pyopenms\_all_modules.py", line 1, in <module>
    from ._pyopenms_1 import *  # pylint: disable=wildcard-import; lgtm(py/polluting-import)
ImportError: DLL load failed while importing _pyopenms_1: A dynamic link library (DLL) initialization routine failed.

**Comment by enthus1ast** [comment]
> Your CPU does not support certain SIMD (AVX?) instructions

This was the issue in my case.
I am virtualizing some windows machines with proxmox, and the default cpu (`x86-64-v2-AES`) does not support `AVX`.
Luckily the host cpu itself does support `AVX`. So the fix for me was to change the CPU (in proxmox) from `x86-64-v2-AES` to `host`.
I think `x86-64-v3` should also work since `AVX` is listed as the feature-set ( https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels ) but it was not working for me, but `host` did

Edit:
On linux you can test this with:
`cat /proc/cpuinfo | grep -i avx`

On windows i've used cpuz and looked in the "flags" area.

**Comment by Andre-C-M** [comment]
Getting this using fragpipe, AVX is supported with my setup. thx

`Error when loading pyOpenMS libraries!
Libraries could not be found / could not be loaded.

To debug this error, please run ldd (on linux), otool -L (on macOS) or dependency walker (on windows) on

.....AppData\Local\anaconda3\Lib\site-packages\pyopenms\pyopenms*.so

======================================================================
PyQt5 was found to be installed. When building pyopenms qmake said:

QMake version 3.1
Using Qt version 5.12.6 in D:/a/OpenMS/Qt/5.12.6/msvc2017_64/lib

PYQT has version 5.15.10

This might cause a conflict if both are loaded. You can test this by importing pyopenms
first and then import PyQt5.QtCore.

Note: when using the Spyder IDE, the usage of PyQt might be circumvented
by not using the 'Automatic' backend. Please change this in Tools ->
Preferences -> IPython -> Graphics to 'Inline'.
In general, try to install everything with conda in the same environment to make sure Qt is used in the same version.
`

**Comment by Andre-C-M** [comment]
the following fixed it for me: 
I was using a freshly installed Anaconda base (root) environment which caused it not to work.
I created a new environment. Within fragpipe, clicking 'Install/Upgrade EasyPQP,' all dependencies and versions will be installed properly.
This may help reconstruct the issue.
![image](https://github.com/user-attachments/assets/7ead80f8-9819-45ae-a565-de676a585adc)

**Comment by timosachsenberg** [comment]
I think this might be fixed. feel free to reopen if not
