### ISSUE TITLE
FeatureFinderCentroided sporadically fails with SIGABRT due to memory corruption

### ISSUE THREAD

**Issue by aiche** [OpenMS/OpenMS#908]
Taken from mailing list post https://sourceforge.net/p/open-ms/mailman/message/32623989/

------
From: Archie Cobbs - 2014-07-18 19:42:05
[Open-ms-general] FeatureFinderCentroided crash due to "double free or corruption"

We are seeing sporadic crashes of FeatureFinderCentroided due to SIGABRT from memory corruption.

I am able to reproduce the problem in gdb, though it requires several tries.

Here's a back trace with debug info:

```
(gdb) where
#0  0x00007ffff4f10849 in raise () from /lib64/libc.so.6
#1  0x00007ffff4f11cd8 in abort () from /lib64/libc.so.6
#2  0x00007ffff4f4f114 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff4f5496e in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff4f55647 in _int_free () from /lib64/libc.so.6
#5  0x00007ffff5c908b9 in std::string::assign(std::string const&) () from /usr/lib64/libstdc++.so.6
#6  0x00007ffff7207508 in OpenMS::Exception::GlobalExceptionHandler::set(std::string const&, int, std::string const&, std::string const&, std::string const&) () from /usr/lib64/libOpenMS.so
#7  0x00007ffff71ef800 in OpenMS::Exception::BaseException::BaseException(char const*, int, char const*, std::string const&, std::string const&) () from /usr/lib64/libOpenMS.so
#8  0x00007ffff71efcba in OpenMS::Exception::Precondition::Precondition(char const*, int, char const*, std::string const&) () from /usr/lib64/libOpenMS.so
#9  0x0000000000445a01 in OpenMS::FeatureFinderAlgorithmPicked<OpenMS::Peak1D, OpenMS::Feature>::extendMassTrace_(OpenMS::FeatureFinderAlgorithmPickedHelperStructs::MassTrace<OpenMS::Peak1D>&, long, double, bool, unsigned long, double, double) const [clone .constprop.2048] ()
#10 0x000000000047ef52 in OpenMS::FeatureFinderAlgorithmPicked<OpenMS::Peak1D, OpenMS::Feature>::extendMassTraces_(OpenMS::FeatureFinderAlgorithmPickedHelperStructs::IsotopePattern const&, OpenMS::FeatureFinderAlgorithmPickedHelperStructs::MassTraces<OpenMS::Peak1D>&, unsigned long) const ()
#11 0x0000000000446e63 in OpenMS::FeatureFinderAlgorithmPicked<OpenMS::Peak1D, OpenMS::Feature>::run() [clone ._omp_fn.0] ()
#12 0x00007ffff56c7f7b in ?? () from /usr/lib64/libgomp.so.1
#13 0x00007ffff52920db in start_thread () from /lib64/libpthread.so.0
#14 0x00007ffff4fc290d in clone () from /lib64/libc.so.6
```

I'm not a C++ programmer (C and Java though) so I'm not sure how to interpret the above. It looks like there are two bugs: first some precondition failed, and then a memory corruption bug happened (or was detected) when the precondition attempted to throw an exception... ?

If any OpenMS developer has a patch that I could apply to help debug this, or wants to otherwise collaborate in fixing it, I'm happy to help. I'd debug it myself bug I just don't know enough about C++.

Thanks,
-Archie

**Comment by hroest** [comment]
@timosachsenberg @aiche can we close this issue now? We have opened an issue #913 for the underlying problem in the exception handler

**Comment by timosachsenberg** [comment]
I think we can close it.
